#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    
    #line 6 "..\..\Views\Actions\Old\Action.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Actions\Old\Action.cshtml"
    using Realtair.Framework.Core.Actions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Actions\Old\Action.cshtml"
    using Realtair.Framework.Core.Entities;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Actions\Old\Action.cshtml"
    using Realtair.Framework.Core.Interfaces;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Actions\Old\Action.cshtml"
    using Realtair.Framework.Core.Web.Utilities;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Actions/Old/Action.cshtml")]
    public partial class _Views_Actions_Old_Action_cshtml : System.Web.Mvc.WebViewPage<Realtair.Framework.Core.Web.Controllers.ActionsController.ActionViewModel>
    {
        public _Views_Actions_Old_Action_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Actions\Old\Action.cshtml"
  
    var detailsTemplate = "-";
    var cancelActionUrl = "";

    if (Request.QueryString["ReturnUrl"] != null)
    {
        cancelActionUrl = Request.QueryString["ReturnUrl"].ToString();
    }

    if (Model.Action.This != null)
    {
        detailsTemplate = $"{Model.Action.This.ActualType().Name}/{Model.Action.GetType().Name}";
    }

    if (Html.ViewExists(detailsTemplate))
    {
        Layout = null;
        Html.RenderPartial(detailsTemplate, Model.Action);
    }
    else
    {
        IEnumerable<Field> shown;
        IEnumerable<Field> shownWithFieldSets;
        IEnumerable<Field> hidden;

        TempData["ShowSubmit"] = true;

        if (Model.IsMultiPage)
        {
            shown = Model.FieldsForPage;
            shownWithFieldSets = Model.FieldsForPage.Where(f => f.FieldSetAttribute != null).ToList();
            hidden = Model.HiddenFieldsForPage;
        }
        else
        {
            shown = Model.Fields;
            shownWithFieldSets = Model.Fields.Where(f => f.FieldSetAttribute != null).ToList();
            hidden = null;
        }


        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Actions\Old\Action.cshtml"
   Write(Html.Partial("Menu"));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Actions\Old\Action.cshtml"
                             


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" id=\"page-wrapper\"");

WriteLiteral(" class=\"with-background\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n");

            
            #line 56 "..\..\Views\Actions\Old\Action.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Actions\Old\Action.cshtml"
                         if (Model.IsMultiPage)
                        {
                            
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Actions\Old\Action.cshtml"
                       Write(Model.Page.Name.ToUpper());

            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Actions\Old\Action.cshtml"
                                                      
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Actions\Old\Action.cshtml"
                       Write(Model.Action.Description(Html.LoggedInUser()).ToUpper());

            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                    
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                    ");

WriteLiteral("\r\n");

            
            #line 66 "..\..\Views\Actions\Old\Action.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 66 "..\..\Views\Actions\Old\Action.cshtml"
                     if (Model.Action.HasValidated && !Model.Action.IsValid)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" style=\"padding: 0;\"");

WriteLiteral(">\r\n");

            
            #line 69 "..\..\Views\Actions\Old\Action.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Actions\Old\Action.cshtml"
                             foreach (var error in Model.Action.Errors.Where(e => e.MemberNames.Count() == 0))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">");

            
            #line 71 "..\..\Views\Actions\Old\Action.cshtml"
                                                           Write(error.ErrorMessage);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 72 "..\..\Views\Actions\Old\Action.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

            
            #line 74 "..\..\Views\Actions\Old\Action.cshtml"
                    }
                    
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Actions\Old\Action.cshtml"
                              

            
            #line default
            #line hidden
WriteLiteral("                    <form");

WriteLiteral(" class=\"autoform form-horizontal main-form\"");

WriteLiteral(" id=\"main-form\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

            
            #line 78 "..\..\Views\Actions\Old\Action.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\Actions\Old\Action.cshtml"
                             foreach (var field in shown)
                            {
                                if (field.FieldSetAttribute != null)
                                {
                                    var fieldSetItems = shownWithFieldSets.Where(s => s.FieldSetAttribute.Legend == field.FieldSetAttribute.Legend).ToList();
                                    if (fieldSetItems.Any())
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <fieldset");

WriteLiteral(" style=\"padding: 1px;\"");

WriteLiteral(">\r\n                                            <legend>");

            
            #line 86 "..\..\Views\Actions\Old\Action.cshtml"
                                               Write(field.FieldSetAttribute.Legend);

            
            #line default
            #line hidden
WriteLiteral("</legend>\r\n                                            <div");

WriteLiteral(" class=\"p-l-30\"");

WriteLiteral(">\r\n");

            
            #line 88 "..\..\Views\Actions\Old\Action.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Actions\Old\Action.cshtml"
                                                 foreach (var item in fieldSetItems)
                                                {
                                                    var fieldWithReturnType = $"Fields/Settings/_{item.PropertyType.Name}_{item.FieldAttribute.GetType().Name.Substring(0, item.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                                    var fieldWithoutReturnType = $"Fields/Settings/_{item.FieldAttribute.GetType().Name.Substring(0, item.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                                    var fieldThatWorksForBoth = $"Fields/Settings/_{item.PropertyType.Name}_Field";

                                                    if (Html.ViewExists(fieldWithReturnType))
                                                    {
                                                        Html.RenderPartial(fieldWithReturnType, item);
                                                    }
                                                    else if (Html.ViewExists(fieldWithoutReturnType))
                                                    {
                                                        Html.RenderPartial(fieldWithoutReturnType, item);
                                                    }
                                                    else if (Html.ViewExists(fieldThatWorksForBoth))
                                                    {
                                                        Html.RenderPartial(fieldThatWorksForBoth, item);
                                                    }
                                                    else
                                                    {


            
            #line default
            #line hidden
WriteLiteral("                                                        <p> Cannot render field v" +
"iew, looked for both ");

            
            #line 109 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                 Write(fieldWithReturnType);

            
            #line default
            #line hidden
WriteLiteral(" and ");

            
            #line 109 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                          Write(fieldWithoutReturnType);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n");

            
            #line 110 "..\..\Views\Actions\Old\Action.cshtml"

                                                    }
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </div>\r\n                             " +
"           </fieldset>");

            
            #line 114 "..\..\Views\Actions\Old\Action.cshtml"
                                                   shownWithFieldSets = shownWithFieldSets.Except(fieldSetItems).ToList();
                                    }
                                }
                                else
                                {
                                    var fieldWithReturnType = $"Fields/Settings/_{field.PropertyType.Name}_{field.FieldAttribute.GetType().Name.Substring(0, field.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                    var fieldWithoutReturnType = $"Fields/Settings/_{field.FieldAttribute.GetType().Name.Substring(0, field.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                    var fieldThatWorksForBoth = $"Fields/Settings/_{field.PropertyType.Name}_Field";

                                    if (Html.ViewExists(fieldWithReturnType))
                                    {
                                        Html.RenderPartial(fieldWithReturnType, field);
                                    }
                                    else if (Html.ViewExists(fieldWithoutReturnType))
                                    {
                                        Html.RenderPartial(fieldWithoutReturnType, field);
                                    }
                                    else if (Html.ViewExists(fieldThatWorksForBoth))
                                    {
                                        Html.RenderPartial(fieldThatWorksForBoth, field);
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <p>Cannot render field view, looked for b" +
"oth ");

            
            #line 137 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                Write(fieldWithReturnType);

            
            #line default
            #line hidden
WriteLiteral(" and ");

            
            #line 137 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                         Write(fieldWithoutReturnType);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 138 "..\..\Views\Actions\Old\Action.cshtml"
                                    }
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 142 "..\..\Views\Actions\Old\Action.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 142 "..\..\Views\Actions\Old\Action.cshtml"
                             if (hidden != null)
                            {
                                foreach (var field in hidden)
                                {
                                    if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.BulkFileUploadFieldAttribute && field.Value is IEnumerable<Attachment>)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral("  type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 7903), Tuple.Create("\"", 7927)
            
            #line 148 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 7910), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 7910), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 7928), Tuple.Create("\"", 8014)
, Tuple.Create(Tuple.Create("", 7936), Tuple.Create("[", 7936), true)
, Tuple.Create(Tuple.Create("", 7937), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 148 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                foreach (var a in field.Value as IEnumerable<Attachment>) { 
            
            #line default
            #line hidden
            
            #line 148 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                      WriteTo(__razor_attribute_value_writer, a.Id + ",");

            
            #line default
            #line hidden
            
            #line 148 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                                                                          }
            
            #line default
            #line hidden
}), 7937), false)
, Tuple.Create(Tuple.Create("", 8013), Tuple.Create("]", 8013), true)
);

WriteLiteral(" />\r\n");

            
            #line 149 "..\..\Views\Actions\Old\Action.cshtml"
                                    }
                                    else if (field.Value is IList<Attachment>)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral("  type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 8239), Tuple.Create("\"", 8263)
            
            #line 152 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 8246), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 8246), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 8264), Tuple.Create("\"", 8355)
, Tuple.Create(Tuple.Create("", 8272), Tuple.Create("[", 8272), true)
            
            #line 152 "..\..\Views\Actions\Old\Action.cshtml"
                , Tuple.Create(Tuple.Create("", 8273), Tuple.Create<System.Object, System.Int32>(string.Join(",",((IList<Attachment>)field.Value).Select(f => f.Id.ToString()))
            
            #line default
            #line hidden
, 8273), false)
, Tuple.Create(Tuple.Create("", 8354), Tuple.Create("]", 8354), true)
);

WriteLiteral(" />\r\n");

            
            #line 153 "..\..\Views\Actions\Old\Action.cshtml"
                                    }
                                    else if (field.Value is ICustomViewModel)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 8578), Tuple.Create("\"", 8602)
            
            #line 156 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 8585), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 8585), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 8603), Tuple.Create("\"", 8659)
            
            #line 156 "..\..\Views\Actions\Old\Action.cshtml"
              , Tuple.Create(Tuple.Create("", 8611), Tuple.Create<System.Object, System.Int32>((field.Value as ICustomViewModel).Serialize()
            
            #line default
            #line hidden
, 8611), false)
);

WriteLiteral(" />\r\n");

            
            #line 157 "..\..\Views\Actions\Old\Action.cshtml"
                                    }
                                    else if (field.Value is IEnumerable<ICustomViewModel>)
                                    {
                                        if ((field.Value as IEnumerable<ICustomViewModel>).Count() > 0)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 9047), Tuple.Create("\"", 9071)
            
            #line 162 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 9054), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 9054), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 9072), Tuple.Create("\"", 9176)
, Tuple.Create(Tuple.Create("", 9080), Tuple.Create("[", 9080), true)
            
            #line 162 "..\..\Views\Actions\Old\Action.cshtml"
                   , Tuple.Create(Tuple.Create("", 9081), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<ICustomViewModel>).Select(s => s.Serialize()))
            
            #line default
            #line hidden
, 9081), false)
, Tuple.Create(Tuple.Create("", 9175), Tuple.Create("]", 9175), true)
);

WriteLiteral(" />\r\n");

            
            #line 163 "..\..\Views\Actions\Old\Action.cshtml"
                                        }
                                    }
                                    else if (field.Value is IEnumerable<Entity>)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 9445), Tuple.Create("\"", 9469)
            
            #line 167 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 9452), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 9452), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 9470), Tuple.Create("\"", 9566)
, Tuple.Create(Tuple.Create("", 9478), Tuple.Create("[", 9478), true)
            
            #line 167 "..\..\Views\Actions\Old\Action.cshtml"
               , Tuple.Create(Tuple.Create("", 9479), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<Entity>).Select(e => e.Id.ToString()))
            
            #line default
            #line hidden
, 9479), false)
, Tuple.Create(Tuple.Create("", 9565), Tuple.Create("]", 9565), true)
);

WriteLiteral(" />\r\n");

            
            #line 168 "..\..\Views\Actions\Old\Action.cshtml"
                                    }
                                    else if (field.Value is Entity)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 9779), Tuple.Create("\"", 9803)
            
            #line 171 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 9786), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 9786), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 9804), Tuple.Create("\"", 9841)
            
            #line 171 "..\..\Views\Actions\Old\Action.cshtml"
              , Tuple.Create(Tuple.Create("", 9812), Tuple.Create<System.Object, System.Int32>((field.Value as Entity).Id
            
            #line default
            #line hidden
, 9812), false)
);

WriteLiteral(" />\r\n");

            
            #line 172 "..\..\Views\Actions\Old\Action.cshtml"
                                    }
                                    else if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.WidgetFieldAttribute)
                                    {

                                    }
                                    else if (field.Value is bool?[])
                                    {
                                        var values = "";
                                        foreach (var v in (field.Value as IEnumerable<bool?>).ToList())
                                        {
                                            if (v != null) { values += v + ","; }
                                            else { values += "null,"; }

                                        }

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral("  type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 10683), Tuple.Create("\"", 10707)
            
            #line 186 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 10690), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 10690), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 10708), Tuple.Create("\"", 10769)
, Tuple.Create(Tuple.Create("", 10716), Tuple.Create("[", 10716), true)
            
            #line 186 "..\..\Views\Actions\Old\Action.cshtml"
               , Tuple.Create(Tuple.Create("", 10717), Tuple.Create<System.Object, System.Int32>(values.Substring(0, values.Length - 1).ToLower()
            
            #line default
            #line hidden
, 10717), false)
, Tuple.Create(Tuple.Create("", 10768), Tuple.Create("]", 10768), true)
);

WriteLiteral(" />\r\n");

            
            #line 187 "..\..\Views\Actions\Old\Action.cshtml"
                                    }
                                    else if (field.Value is DateTime)
                                    {
                                        var date = (DateTime)field.Value;

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 11059), Tuple.Create("\"", 11083)
            
            #line 191 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 11066), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 11066), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 11084), Tuple.Create("\"", 11154)
, Tuple.Create(Tuple.Create("", 11092), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 191 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                              if(date > DateTime.MinValue) { 
            
            #line default
            #line hidden
            
            #line 191 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                      WriteTo(__razor_attribute_value_writer, date.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
            
            #line 191 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                                                          }
            
            #line default
            #line hidden
}), 11092), false)
);

WriteLiteral(" />\r\n");

            
            #line 192 "..\..\Views\Actions\Old\Action.cshtml"
                                    }
                                    else if (field.Value is bool)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 11365), Tuple.Create("\"", 11389)
            
            #line 195 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 11372), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 11372), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 11390), Tuple.Create("\"", 11421)
            
            #line 195 "..\..\Views\Actions\Old\Action.cshtml"
            , Tuple.Create(Tuple.Create("", 11398), Tuple.Create<System.Object, System.Int32>(field.Value.ToString()
            
            #line default
            #line hidden
, 11398), false)
);

WriteLiteral(" />\r\n");

            
            #line 196 "..\..\Views\Actions\Old\Action.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 11607), Tuple.Create("\"", 11631)
            
            #line 199 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 11614), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 11614), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 11632), Tuple.Create("\"", 11652)
            
            #line 199 "..\..\Views\Actions\Old\Action.cshtml"
            , Tuple.Create(Tuple.Create("", 11640), Tuple.Create<System.Object, System.Int32>(field.Value
            
            #line default
            #line hidden
, 11640), false)
);

WriteLiteral(" />\r\n");

            
            #line 200 "..\..\Views\Actions\Old\Action.cshtml"
                                    }
                                }


            
            #line default
            #line hidden
WriteLiteral("                                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"submittedpagenames\"");

WriteAttribute("value", Tuple.Create(" value=\"", 11812), Tuple.Create("\"", 11889)
            
            #line 203 "..\..\Views\Actions\Old\Action.cshtml"
     , Tuple.Create(Tuple.Create("", 11820), Tuple.Create<System.Object, System.Int32>(string.Join(",", Model.SubmittedPages.Select(p => p.GetType().Name))
            
            #line default
            #line hidden
, 11820), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"page\"");

WriteAttribute("value", Tuple.Create(" value=\"", 11959), Tuple.Create("\"", 11993)
            
            #line 204 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 11967), Tuple.Create<System.Object, System.Int32>(Model.Page.GetType().Name
            
            #line default
            #line hidden
, 11967), false)
);

WriteLiteral(" />\r\n");

            
            #line 205 "..\..\Views\Actions\Old\Action.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" style=\"position: absolute; left: -9999px; width: 1px; height: 1px;\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </form>\r\n\r\n");

            
            #line 211 "..\..\Views\Actions\Old\Action.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 211 "..\..\Views\Actions\Old\Action.cshtml"
                     if ((bool)TempData["ShowSubmit"] || Model.SubmittedPages.Count != 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n");

            
            #line 214 "..\..\Views\Actions\Old\Action.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 214 "..\..\Views\Actions\Old\Action.cshtml"
                             if ((bool)TempData["ShowSubmit"])
                            {
                                
            
            #line default
            #line hidden
            
            #line 216 "..\..\Views\Actions\Old\Action.cshtml"
                                 if (!Model.IsMultiPage)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" data-next");

WriteLiteral(" class=\"btn btn-primary pull-right m-l-20 main-form\"");

WriteLiteral(" id=\"main-form-submit\"");

WriteLiteral(">");

            
            #line 218 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                                         Write(Model.Action.SubmitValue);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 219 "..\..\Views\Actions\Old\Action.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" data-next");

WriteLiteral(" class=\"btn btn-primary pull-right m-l-20 main-form\"");

WriteLiteral(" id=\"main-form-submit\"");

WriteLiteral(">");

            
            #line 222 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                                         Write(Model.Page.SubmitValue);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 223 "..\..\Views\Actions\Old\Action.cshtml"
                                }
            
            #line default
            #line hidden
            
            #line 223 "..\..\Views\Actions\Old\Action.cshtml"
                                 

                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 227 "..\..\Views\Actions\Old\Action.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 227 "..\..\Views\Actions\Old\Action.cshtml"
                             if (Model.SubmittedPages.Count != 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <button");

WriteLiteral(" class=\"btn btn-default pull-right\"");

WriteLiteral(" onclick=\'$(\"#back-form\").submit();\'");

WriteLiteral(">Back</button>\r\n");

            
            #line 230 "..\..\Views\Actions\Old\Action.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <button");

WriteLiteral(" class=\"btn btn-default pull-right\"");

WriteLiteral(" onclick=\'$(\"#cancel-form\").submit();\'");

WriteLiteral(">Cancel</button>\r\n");

            
            #line 234 "..\..\Views\Actions\Old\Action.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n                        </div>\r\n");

            
            #line 238 "..\..\Views\Actions\Old\Action.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 240 "..\..\Views\Actions\Old\Action.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 240 "..\..\Views\Actions\Old\Action.cshtml"
                     if (Model.IsMultiPage)
                    {
                        if (Model.SubmittedPages.Count != 0)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" id=\"back-form\"");

WriteLiteral(">\r\n");

            
            #line 245 "..\..\Views\Actions\Old\Action.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 245 "..\..\Views\Actions\Old\Action.cshtml"
                                 if (hidden != null)
                                {
                                    foreach (var field in hidden)
                                    {
                                        if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.BulkFileUploadFieldAttribute && field.Value is IEnumerable<Attachment>)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 14427), Tuple.Create("\"", 14451)
            
            #line 251 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 14434), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 14434), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 14452), Tuple.Create("\"", 14538)
, Tuple.Create(Tuple.Create("", 14460), Tuple.Create("[", 14460), true)
, Tuple.Create(Tuple.Create("", 14461), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 251 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                   foreach (var a in field.Value as IEnumerable<Attachment>) { 
            
            #line default
            #line hidden
            
            #line 251 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                         WriteTo(__razor_attribute_value_writer, a.Id + ",");

            
            #line default
            #line hidden
            
            #line 251 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                                                                             }
            
            #line default
            #line hidden
}), 14461), false)
, Tuple.Create(Tuple.Create("", 14537), Tuple.Create("]", 14537), true)
);

WriteLiteral(" />\r\n");

            
            #line 252 "..\..\Views\Actions\Old\Action.cshtml"
                                        }
                                        else if (field.Value is IEnumerable<Attachment>)
                                        {
                                            foreach (var file in (IEnumerable<Attachment>)field.Value)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 14939), Tuple.Create("\"", 14963)
            
            #line 257 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 14946), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 14946), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 14964), Tuple.Create("\"", 14982)
            
            #line 257 "..\..\Views\Actions\Old\Action.cshtml"
                     , Tuple.Create(Tuple.Create("", 14972), Tuple.Create<System.Object, System.Int32>(file.Id
            
            #line default
            #line hidden
, 14972), false)
);

WriteLiteral(" />");

            
            #line 257 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                   }
                                        }
                                        else if (field.Value is ICustomViewModel)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 15222), Tuple.Create("\"", 15246)
            
            #line 261 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 15229), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 15229), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 15247), Tuple.Create("\"", 15303)
            
            #line 261 "..\..\Views\Actions\Old\Action.cshtml"
                 , Tuple.Create(Tuple.Create("", 15255), Tuple.Create<System.Object, System.Int32>((field.Value as ICustomViewModel).Serialize()
            
            #line default
            #line hidden
, 15255), false)
);

WriteLiteral(" />\r\n");

            
            #line 262 "..\..\Views\Actions\Old\Action.cshtml"
                                        }
                                        else if (field.Value is IEnumerable<ICustomViewModel>)
                                        {
                                            if ((field.Value as IEnumerable<ICustomViewModel>).Count() > 0)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 15715), Tuple.Create("\"", 15739)
            
            #line 267 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 15722), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 15722), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 15740), Tuple.Create("\"", 15844)
, Tuple.Create(Tuple.Create("", 15748), Tuple.Create("[", 15748), true)
            
            #line 267 "..\..\Views\Actions\Old\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 15749), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<ICustomViewModel>).Select(s => s.Serialize()))
            
            #line default
            #line hidden
, 15749), false)
, Tuple.Create(Tuple.Create("", 15843), Tuple.Create("]", 15843), true)
);

WriteLiteral(" />");

            
            #line 267 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                                                                                                         }
                                        }
                                        else if (field.Value is Entity)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 16074), Tuple.Create("\"", 16098)
            
            #line 271 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 16081), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 16081), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 16099), Tuple.Create("\"", 16136)
            
            #line 271 "..\..\Views\Actions\Old\Action.cshtml"
                 , Tuple.Create(Tuple.Create("", 16107), Tuple.Create<System.Object, System.Int32>((field.Value as Entity).Id
            
            #line default
            #line hidden
, 16107), false)
);

WriteLiteral(" />\r\n");

            
            #line 272 "..\..\Views\Actions\Old\Action.cshtml"
                                        }
                                        else if (field.Value is IEnumerable<Entity>)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 16378), Tuple.Create("\"", 16402)
            
            #line 275 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 16385), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 16385), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 16403), Tuple.Create("\"", 16499)
, Tuple.Create(Tuple.Create("", 16411), Tuple.Create("[", 16411), true)
            
            #line 275 "..\..\Views\Actions\Old\Action.cshtml"
                  , Tuple.Create(Tuple.Create("", 16412), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<Entity>).Select(e => e.Id.ToString()))
            
            #line default
            #line hidden
, 16412), false)
, Tuple.Create(Tuple.Create("", 16498), Tuple.Create("]", 16498), true)
);

WriteLiteral(" />\r\n");

            
            #line 276 "..\..\Views\Actions\Old\Action.cshtml"
                                        }
                                        else if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.WidgetFieldAttribute)
                                        {

                                        }
                                        else if (field.Value is bool?[])
                                        {
                                            var values = "";
                                            foreach (var v in (field.Value as IEnumerable<bool?>).ToList())
                                            {
                                                if (v != null) { values += v + ","; }
                                                else { values += "null,"; }

                                            }

            
            #line default
            #line hidden
WriteLiteral("                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 17392), Tuple.Create("\"", 17416)
            
            #line 290 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 17399), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 17399), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 17417), Tuple.Create("\"", 17478)
, Tuple.Create(Tuple.Create("", 17425), Tuple.Create("[", 17425), true)
            
            #line 290 "..\..\Views\Actions\Old\Action.cshtml"
                  , Tuple.Create(Tuple.Create("", 17426), Tuple.Create<System.Object, System.Int32>(values.Substring(0, values.Length - 1).ToLower()
            
            #line default
            #line hidden
, 17426), false)
, Tuple.Create(Tuple.Create("", 17477), Tuple.Create("]", 17477), true)
);

WriteLiteral(" />\r\n");

            
            #line 291 "..\..\Views\Actions\Old\Action.cshtml"
                                        }
                                        else if (field.Value is DateTime)
                                        {
                                            var date = (DateTime)field.Value;

            
            #line default
            #line hidden
WriteLiteral("                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 17788), Tuple.Create("\"", 17812)
            
            #line 295 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 17795), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 17795), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 17813), Tuple.Create("\"", 17883)
, Tuple.Create(Tuple.Create("", 17821), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 295 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                  if(date > DateTime.MinValue) { 
            
            #line default
            #line hidden
            
            #line 295 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                          WriteTo(__razor_attribute_value_writer, date.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
            
            #line 295 "..\..\Views\Actions\Old\Action.cshtml"
                                                                                                                                                              }
            
            #line default
            #line hidden
}), 17821), false)
);

WriteLiteral(" />\r\n");

            
            #line 296 "..\..\Views\Actions\Old\Action.cshtml"
                                        }
                                        else if (field.Value is bool)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 18110), Tuple.Create("\"", 18134)
            
            #line 299 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 18117), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 18117), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 18135), Tuple.Create("\"", 18166)
            
            #line 299 "..\..\Views\Actions\Old\Action.cshtml"
                , Tuple.Create(Tuple.Create("", 18143), Tuple.Create<System.Object, System.Int32>(field.Value.ToString()
            
            #line default
            #line hidden
, 18143), false)
);

WriteLiteral(" />\r\n");

            
            #line 300 "..\..\Views\Actions\Old\Action.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 18368), Tuple.Create("\"", 18392)
            
            #line 303 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 18375), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 18375), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 18393), Tuple.Create("\"", 18413)
            
            #line 303 "..\..\Views\Actions\Old\Action.cshtml"
                , Tuple.Create(Tuple.Create("", 18401), Tuple.Create<System.Object, System.Int32>(field.Value
            
            #line default
            #line hidden
, 18401), false)
);

WriteLiteral(" />\r\n");

            
            #line 304 "..\..\Views\Actions\Old\Action.cshtml"
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"submittedpagenames\"");

WriteAttribute("value", Tuple.Create(" value=\"", 18583), Tuple.Create("\"", 18660)
            
            #line 306 "..\..\Views\Actions\Old\Action.cshtml"
         , Tuple.Create(Tuple.Create("", 18591), Tuple.Create<System.Object, System.Int32>(string.Join(",", Model.SubmittedPages.Select(p => p.GetType().Name))
            
            #line default
            #line hidden
, 18591), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"page\"");

WriteAttribute("value", Tuple.Create(" value=\"", 18734), Tuple.Create("\"", 18768)
            
            #line 307 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 18742), Tuple.Create<System.Object, System.Int32>(Model.Page.GetType().Name
            
            #line default
            #line hidden
, 18742), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"back\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n");

            
            #line 309 "..\..\Views\Actions\Old\Action.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </form>\r\n");

            
            #line 311 "..\..\Views\Actions\Old\Action.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" id=\"cancel-form\"");

WriteAttribute("action", Tuple.Create(" action=\"", 19038), Tuple.Create("\"", 19065)
            
            #line 313 "..\..\Views\Actions\Old\Action.cshtml"
, Tuple.Create(Tuple.Create("", 19047), Tuple.Create<System.Object, System.Int32>(cancelActionUrl
            
            #line default
            #line hidden
, 19047), false)
);

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"cancel\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n                    </form>\r\n                </div>\r\n\r\n            </div>\r\n " +
"       </div>\r\n");

            
            #line 320 "..\..\Views\Actions\Old\Action.cshtml"
        
            
            #line default
            #line hidden
            
            #line 320 "..\..\Views\Actions\Old\Action.cshtml"
   Write(Html.Partial("Footer"));

            
            #line default
            #line hidden
            
            #line 320 "..\..\Views\Actions\Old\Action.cshtml"
                               

            
            #line default
            #line hidden
WriteLiteral(@"        <script>
            $(document).ready(function () {
                var firstInput = $('form').find('input[type=text],input[type=password],input[type=radio],input[type=checkbox],textarea,select').filter(':visible:first');
                if (firstInput != null) {
                    firstInput.focus();
                }
            });

            $('#main-form-submit').click(function (e) {
				e.preventDefault()
				var bValid = true;
				$(document).find('input.required:visible').each(function () {
					var formgroup = $(this).closest('.form-group');
					if ($(this).val() === '') {
						formgroup.addClass('has-error');
						var label = formgroup.find('label.control-label').text();

						console.log(formgroup.find('div').index(0));
						if ($(this).closest('.col-md-9').find('span.help-block').length == 0)
							$(this).closest('.col-md-9').append('<span class=""help-block"">The ' + label + ' field is required.</span>');

						bValid = false;
					} else {
						formgroup.removeClass('has-error');
						formgroup.find('span.help-block').remove();
					}
				});
				if (bValid) {
					$('.preloader').css('display', 'block');
					$('#main-form').submit.disabled = true;
					$('#main-form').submit();
                }
			});
        </script>
");

            
            #line 355 "..\..\Views\Actions\Old\Action.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 359 "..\..\Views\Actions\Old\Action.cshtml"
Write(Html.RenderDelayed());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
