#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Realtair.Framework.Core.Actions;
    using Realtair.Framework.Core.Entities;
    
    #line 3 "..\..\Views\Details\Details.cshtml"
    using Realtair.Framework.Core.Entities.Display;
    
    #line default
    #line hidden
    using Realtair.Framework.Core.Interfaces;
    
    #line 2 "..\..\Views\Details\Details.cshtml"
    using Realtair.Framework.Core.Web.Utilities;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Details\Details.cshtml"
    using Realtair.Framework.Enquiries.Entities;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Details/Details.cshtml")]
    public partial class _Views_Details_Details_cshtml : System.Web.Mvc.WebViewPage<Realtair.Framework.Core.Interfaces.IDisplayable>
    {

#line 194 "..\..\Views\Details\Details.cshtml"
public System.Web.WebPages.HelperResult Render(object describable)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 195 "..\..\Views\Details\Details.cshtml"
 
if (describable == null)
{
        

#line default
#line hidden

#line 198 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, "N/A");


#line default
#line hidden

#line 198 "..\..\Views\Details\Details.cshtml"
                
}
else if (describable is string)
{
        

#line default
#line hidden

#line 202 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, describable);


#line default
#line hidden

#line 202 "..\..\Views\Details\Details.cshtml"
                    
}
else if (describable is decimal || describable is double || describable is int)
{
        

#line default
#line hidden

#line 206 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, describable.ToString());


#line default
#line hidden

#line 206 "..\..\Views\Details\Details.cshtml"
                               
}
else if (describable is DateTime)
{
        

#line default
#line hidden

#line 210 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, ((DateTime)describable).ToString("d MMM yyyy"));


#line default
#line hidden

#line 210 "..\..\Views\Details\Details.cshtml"
                                                         ;
}
else if (describable is IEnumerable<IDisplayable> || describable is IEnumerable<IHasDisplayable>)
{
    var d = describable as IEnumerable<IDescribable>;
    for (int i = 0; i < d.Count(); i++)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 12560), Tuple.Create("\"", 12615)

#line 217 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 12567), Tuple.Create<System.Object, System.Int32>(d.ElementAt(i).GetUrl(Html.LoggedInUser(), Url)

#line default
#line hidden
, 12567), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 217 "..\..\Views\Details\Details.cshtml"
                                         WriteTo(__razor_helper_writer, d.ElementAt(i).Description(Html.LoggedInUser()));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a>\r\n");


#line 218 "..\..\Views\Details\Details.cshtml"

        if (i < d.Count() - 1)
        {
                

#line default
#line hidden

#line 221 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, " & ");


#line default
#line hidden

#line 221 "..\..\Views\Details\Details.cshtml"
                        ;
        }
    }
}
else if (describable is IDisplayable || describable is IHasDisplayable || describable is Enquiry || describable is IExtendedEnquiry)
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 12911), Tuple.Create("\"", 12983)

#line 227 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 12918), Tuple.Create<System.Object, System.Int32>((describable as IDescribable).GetUrl(Html.LoggedInUser(), Url)

#line default
#line hidden
, 12918), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 227 "..\..\Views\Details\Details.cshtml"
                                                       WriteTo(__razor_helper_writer, (describable as IDescribable).Description(Html.LoggedInUser()));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a>\r\n");


#line 228 "..\..\Views\Details\Details.cshtml"
}
else if (describable is IEnumerable<IDescribable>)
{
    var d = describable as IEnumerable<IDescribable>;
    for (int i = 0; i < d.Count(); i++)
    {
            

#line default
#line hidden

#line 234 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, d.ElementAt(i).Description(Html.LoggedInUser()));


#line default
#line hidden

#line 234 "..\..\Views\Details\Details.cshtml"
                                                            

        if (i < d.Count() - 1)
        {
                

#line default
#line hidden

#line 238 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, " & ");


#line default
#line hidden

#line 238 "..\..\Views\Details\Details.cshtml"
                        ;
        }
    }
}
else if (describable is IDescribable)
{
        

#line default
#line hidden

#line 244 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, (describable as IDescribable).Description(Html.LoggedInUser()));


#line default
#line hidden

#line 244 "..\..\Views\Details\Details.cshtml"
                                                                         
}
else if (describable is Enum)
{
        

#line default
#line hidden

#line 248 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, (describable as Enum).Description());


#line default
#line hidden

#line 248 "..\..\Views\Details\Details.cshtml"
                                              
}



#line default
#line hidden
});

#line 251 "..\..\Views\Details\Details.cshtml"
}
#line default
#line hidden

        public _Views_Details_Details_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<body");

WriteLiteral(" class=\"page-header-hero\"");

WriteLiteral(">\r\n\r\n    <header");

WriteLiteral(" id=\"section-header\"");

WriteLiteral(" class=\"header-admin header-sm main-in-header\"");

WriteLiteral(" role=\"banner\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"bg-header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"overlay-gradient-radial\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"overlay-gradient-linear\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"bg-default\"");

WriteLiteral(" style=\"background-image: url(/content/img/background-desk.jpg)\"");

WriteLiteral("></div>\r\n        </div>\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Details\Details.cshtml"
   Write(Html.Partial("Menu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"header-content\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"title-hero\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Views\Details\Details.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Details\Details.cshtml"
                         if (Model != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                                <h1");

WriteLiteral(" class=\"ellipsis\"");

WriteLiteral(">\r\n                                    <strong>");

            
            #line 25 "..\..\Views\Details\Details.cshtml"
                                       Write(Model.ActualType().Name.DisplaySafeName());

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                                    <small");

WriteLiteral(" class=\"ellipsis\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\Details\Details.cshtml"
                                                       Write(Model.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                                </h1>\r\n                            </di" +
"v>\r\n");

WriteLiteral("                            <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"box-btn\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 32 "..\..\Views\Details\Details.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Details\Details.cshtml"
                                           var offset = 4 - (Model as IActionable)?.Actions().WithAccess(Html.LoggedInUser(), ViewContext.DbContext()).Count() - (Model is IHasSettings ? 1 : 0); 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 33 "..\..\Views\Details\Details.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Details\Details.cshtml"
                                         if (offset > 0)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1758), Tuple.Create("\"", 1796)
, Tuple.Create(Tuple.Create("", 1766), Tuple.Create("hidden-xs", 1766), true)
, Tuple.Create(Tuple.Create(" ", 1775), Tuple.Create("col-sm-", 1776), true)
            
            #line 35 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 1783), Tuple.Create<System.Object, System.Int32>(offset * 3
            
            #line default
            #line hidden
, 1783), false)
);

WriteLiteral(">&nbsp;</div>\r\n");

            
            #line 36 "..\..\Views\Details\Details.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 38 "..\..\Views\Details\Details.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Details\Details.cshtml"
                                         if (Model is IActionable && (Model as IActionable).Actions().WithAccess(Html.LoggedInUser(), ViewContext.DbContext()).Count() >= 1)
                                        {
                                            foreach (var action in (Model as IActionable).Actions().WithAccess(Html.LoggedInUser(), ViewContext.DbContext()))
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <div");

WriteLiteral(" class=\"col-xs-6 col-sm-3\"");

WriteLiteral(">\r\n                                                    <a");

WriteLiteral(" class=\"btn btn-primary ellipsis\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2448), Tuple.Create("\"", 2518)
            
            #line 43 "..\..\Views\Details\Details.cshtml"
              , Tuple.Create(Tuple.Create("", 2455), Tuple.Create<System.Object, System.Int32>(action.GetUrl(Html.LoggedInUser(), Url)
            
            #line default
            #line hidden
, 2455), false)
, Tuple.Create(Tuple.Create("", 2495), Tuple.Create("?", 2495), true)
            
            #line 43 "..\..\Views\Details\Details.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 2496), Tuple.Create<System.Object, System.Int32>(Request.QueryString
            
            #line default
            #line hidden
, 2496), false)
);

WriteLiteral(" title=\"#\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                        ");

            
            #line 44 "..\..\Views\Details\Details.cshtml"
                                                   Write(action.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                    </a>\r\n                     " +
"                           </div>\r\n");

            
            #line 47 "..\..\Views\Details\Details.cshtml"
                                            }
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 50 "..\..\Views\Details\Details.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Details\Details.cshtml"
                                         if (Model is IHasSettings)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" class=\"col-xs-12 col-sm-3\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"btn btn-info ellipsis\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3106), Tuple.Create("\"", 3169)
, Tuple.Create(Tuple.Create("", 3113), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 3113), false)
            
            #line 53 "..\..\Views\Details\Details.cshtml"
         , Tuple.Create(Tuple.Create("", 3115), Tuple.Create<System.Object, System.Int32>(Model.UrlSafeName()
            
            #line default
            #line hidden
, 3115), false)
, Tuple.Create(Tuple.Create("", 3135), Tuple.Create("/", 3135), true)
            
            #line 53 "..\..\Views\Details\Details.cshtml"
                               , Tuple.Create(Tuple.Create("", 3136), Tuple.Create<System.Object, System.Int32>((Model as IEntity).Id
            
            #line default
            #line hidden
, 3136), false)
, Tuple.Create(Tuple.Create("", 3160), Tuple.Create("/settings", 3160), true)
);

WriteLiteral(" title=\"Settings\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"icon icon-Settings\"");

WriteLiteral("></span>&nbsp;&nbsp;Settings\r\n                                                </a" +
">\r\n                                            </div>\r\n");

            
            #line 57 "..\..\Views\Details\Details.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                   " +
" <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n                                </div>\r\n                            </di" +
"v>\r\n");

            
            #line 63 "..\..\Views\Details\Details.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                                    <h1");

WriteLiteral(" class=\"ellipsis\"");

WriteLiteral(">\r\n                                                        <strong>Details Not Fo" +
"und</strong>\r\n                                                    </h1>\r\n       " +
"                                         </div>\r\n");

            
            #line 71 "..\..\Views\Details\Details.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n            </div>\r\n         " +
"   <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n        </div>\r\n    </header>\r\n\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

            
            #line 80 "..\..\Views\Details\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Details\Details.cshtml"
     if (Model != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <main");

WriteLiteral(" role=\"main\"");

WriteLiteral(" class=\"in-header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n");

            
            #line 84 "..\..\Views\Details\Details.cshtml"
                
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Details\Details.cshtml"
                 foreach (var detailWidget in Model.Sections(Html.LoggedInUser()).Where(w => w is DetailWidget))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"panel panel-info\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral("><h2>");

            
            #line 87 "..\..\Views\Details\Details.cshtml"
                                                   Write((detailWidget as DetailWidget).Name);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                        <div");

WriteLiteral(" class=\"panel-wrapper collapse in\"");

WriteLiteral(">\r\n                            <table");

WriteLiteral(" class=\"table table-hover table-striped\"");

WriteLiteral(">\r\n                                <tbody>\r\n");

            
            #line 91 "..\..\Views\Details\Details.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Details\Details.cshtml"
                                     foreach (var describable in (detailWidget as DetailWidget).Details)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <tr>\r\n                                   " +
"         <th");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">");

            
            #line 94 "..\..\Views\Details\Details.cshtml"
                                                            Write(describable.Key);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                            <td");

WriteLiteral(" data-key=\"");

            
            #line 95 "..\..\Views\Details\Details.cshtml"
                                                     Write(describable.Key);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 96 "..\..\Views\Details\Details.cshtml"
                                           Write(Render(describable.Value));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </td>\r\n                            " +
"            </tr>\r\n");

            
            #line 99 "..\..\Views\Details\Details.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </tbody>\r\n                            </table>\r\n " +
"                       </div>\r\n                    </div>\r\n");

            
            #line 104 "..\..\Views\Details\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"panel-wrapper collapse in\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"vtabs customvtab\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"nav tabs-vertical\"");

WriteLiteral(" style=\"width: 0;\"");

WriteLiteral(">\r\n");

            
            #line 111 "..\..\Views\Details\Details.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 111 "..\..\Views\Details\Details.cshtml"
                                     if (Model.Sections(Html.LoggedInUser()).Where(w => w is ListWidget) != null)
                                    {
                                        for (var listNo = 0; listNo < Model.Sections(Html.LoggedInUser()).Where(w => w is ListWidget).Count(); listNo++)
                                        {
                                            var list = Model.Sections(Html.LoggedInUser()).Where(w => w is ListWidget).ElementAt(listNo) as ListWidget;

            
            #line default
            #line hidden
WriteLiteral("                                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 6541), Tuple.Create("\"", 6583)
, Tuple.Create(Tuple.Create("", 6549), Tuple.Create("tab", 6549), true)
            
            #line 116 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create(" ", 6552), Tuple.Create<System.Object, System.Int32>(listNo == 0 ? "active" : ""
            
            #line default
            #line hidden
, 6553), false)
);

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" data-toggle=\"tab\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6655), Tuple.Create("\"", 6674)
, Tuple.Create(Tuple.Create("", 6662), Tuple.Create("#tab-", 6662), true)
            
            #line 117 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 6667), Tuple.Create<System.Object, System.Int32>(listNo
            
            #line default
            #line hidden
, 6667), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                                    ");

            
            #line 118 "..\..\Views\Details\Details.cshtml"
                                               Write(list.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </a>\r\n                         " +
"                   </li>\r\n");

            
            #line 121 "..\..\Views\Details\Details.cshtml"
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                      <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(" style=\"padding: 0;\"");

WriteLiteral(">\r\n");

            
            #line 127 "..\..\Views\Details\Details.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 127 "..\..\Views\Details\Details.cshtml"
                                     for (var listNo = 0; listNo < Model.Sections(Html.LoggedInUser()).Where(w => w is ListWidget).Count(); listNo++)
                                    {
                                        var list = Model.Sections(Html.LoggedInUser()).Where(w => w is ListWidget).ElementAt(listNo) as ListWidget;


            
            #line default
            #line hidden
WriteLiteral("                                        <div");

WriteAttribute("id", Tuple.Create(" id=\"", 7520), Tuple.Create("\"", 7536)
, Tuple.Create(Tuple.Create("", 7525), Tuple.Create("tab-", 7525), true)
            
            #line 131 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 7529), Tuple.Create<System.Object, System.Int32>(listNo
            
            #line default
            #line hidden
, 7529), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 7537), Tuple.Create("\"", 7592)
, Tuple.Create(Tuple.Create("", 7545), Tuple.Create("tab-pane", 7545), true)
, Tuple.Create(Tuple.Create(" ", 7553), Tuple.Create("fade", 7554), true)
, Tuple.Create(Tuple.Create(" ", 7558), Tuple.Create("in", 7559), true)
            
            #line 131 "..\..\Views\Details\Details.cshtml"
      , Tuple.Create(Tuple.Create(" ", 7561), Tuple.Create<System.Object, System.Int32>(listNo == 0 ? "active" : ""
            
            #line default
            #line hidden
, 7562), false)
);

WriteLiteral(">\r\n                                            <h3");

WriteLiteral(" class=\"box-title m-b-0\"");

WriteLiteral(">");

            
            #line 132 "..\..\Views\Details\Details.cshtml"
                                                                   Write(list.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                                            <table");

WriteAttribute("id", Tuple.Create(" id=\"", 7735), Tuple.Create("\"", 7758)
, Tuple.Create(Tuple.Create("", 7740), Tuple.Create("listWidget_", 7740), true)
            
            #line 133 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 7751), Tuple.Create<System.Object, System.Int32>(listNo
            
            #line default
            #line hidden
, 7751), false)
);

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n                                                <thead");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(@">
                                                    <tr>
                                                        <th>&nbsp;</th>
                                                    </tr>
                                                </thead>
                                                <tbody>                                                   
");

            
            #line 140 "..\..\Views\Details\Details.cshtml"
                                                    
            
            #line default
            #line hidden
            
            #line 140 "..\..\Views\Details\Details.cshtml"
                                                     if (list.Items != null || list.Items.Count() > 0)
                                                    {
                                                        foreach (var item in list.Items)
                                                        {

            
            #line default
            #line hidden
WriteLiteral(@"                                                            <tr>
                                                                <td>
                                                                    <div>
                                                                        <div");

WriteLiteral(" class=\"media-left\"");

WriteLiteral(">\r\n                                                                            <a" +
"");

WriteAttribute("href", Tuple.Create(" href=\"", 8920), Tuple.Create("\"", 8965)
            
            #line 148 "..\..\Views\Details\Details.cshtml"
     , Tuple.Create(Tuple.Create("", 8927), Tuple.Create<System.Object, System.Int32>(item.GetUrl(Html.LoggedInUser(), Url)
            
            #line default
            #line hidden
, 8927), false)
);

WriteLiteral(" ");

            
            #line 148 "..\..\Views\Details\Details.cshtml"
                                                                                                                        Write(Html.Raw(item is Attachment ? "target=\"_blank\"" : ""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n                                                                              " +
"  <i");

WriteLiteral(" class=\"ti-user\"");

WriteLiteral(" style=\"font-size: 40px;\"");

WriteLiteral("></i>\r\n                                                                          " +
"  </a>\r\n                                                                        " +
"</div>\r\n                                                                        " +
"<div");

WriteLiteral(" class=\"media-body\"");

WriteLiteral(">\r\n                                                                            <h" +
"4");

WriteLiteral(" class=\"media-heading\"");

WriteLiteral(">");

            
            #line 153 "..\..\Views\Details\Details.cshtml"
                                                                                                 Write(item.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                                                                          " +
"  <em");

WriteLiteral(" class=\"ellipsis\"");

WriteLiteral(">");

            
            #line 154 "..\..\Views\Details\Details.cshtml"
                                                                                            Write(item.ActualType().Name.DisplaySafeName());

            
            #line default
            #line hidden
WriteLiteral(@"</em>
                                                                        </div>
                                                                    </div>
                                                                </td>
                                                            </tr>
");

            
            #line 159 "..\..\Views\Details\Details.cshtml"
                                                        }
                                                    }

            
            #line default
            #line hidden
WriteLiteral("                                                </tbody>\r\n                       " +
"                     </table>\r\n                                            <link" +
"");

WriteLiteral(" href=\"http://static.realtair.com/ample/plugins/bower_components/datatables/jquer" +
"y.dataTables.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n                                            <link");

WriteLiteral(" href=\"https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n\r\n                                            <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"http://static.realtair.com/ample/plugins/bower_components/datatables/jquery" +
".dataTables.min.js\"");

WriteLiteral(" async=\"async\"");

WriteLiteral("></script>\r\n                                            <script");

WriteLiteral(" src=\"https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js\"");

WriteLiteral("></script>\r\n\r\n                                            <script>\r\n             " +
"                                       $(document).ready(function () {\r\n        " +
"                                                //$(\'#listWidget_");

            
            #line 171 "..\..\Views\Details\Details.cshtml"
                                                                    Write(listNo);

            
            #line default
            #line hidden
WriteLiteral(@"').DataTable({
                                                        //    ""bFilter"": true,
                                                        //    ""bInfo"": false,
                                                        //    ""sorting"": false,
                                                        //    ""bLengthChange"": false
                                                        //});
                                                    });
                                            </script>

                                        </div>
");

            
            #line 181 "..\..\Views\Details\Details.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </div>\r\n                            </div>\r\n     " +
"                   </div>\r\n                    </div>\r\n                </div>\r\n " +
"           </div>\r\n        </main>\r\n");

            
            #line 189 "..\..\Views\Details\Details.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
