#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Realtair.Framework.Core.Actions;
    using Realtair.Framework.Core.Entities;
    using Realtair.Framework.Core.Interfaces;
    
    #line 2 "..\..\Views\Details\Details.cshtml"
    using Realtair.Framework.Core.Web.Utilities;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Details\Details.cshtml"
    using Realtair.Framework.Enquiries.Entities;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Details/Details.cshtml")]
    public partial class _Views_Details_Details_cshtml : System.Web.Mvc.WebViewPage<Realtair.Framework.Core.Interfaces.IDisplayable>
    {

#line 185 "..\..\Views\Details\Details.cshtml"
public System.Web.WebPages.HelperResult Render(object describable)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 186 "..\..\Views\Details\Details.cshtml"
 
if (describable == null)
{
        

#line default
#line hidden

#line 189 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, "N/A");


#line default
#line hidden

#line 189 "..\..\Views\Details\Details.cshtml"
                
}
else if (describable is string)
{
        

#line default
#line hidden

#line 193 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, describable);


#line default
#line hidden

#line 193 "..\..\Views\Details\Details.cshtml"
                    
}
else if (describable is decimal || describable is double || describable is int)
{
        

#line default
#line hidden

#line 197 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, describable.ToString());


#line default
#line hidden

#line 197 "..\..\Views\Details\Details.cshtml"
                               
}
else if (describable is DateTime)
{
        

#line default
#line hidden

#line 201 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, ((DateTime)describable).ToString("d MMM yyyy"));


#line default
#line hidden

#line 201 "..\..\Views\Details\Details.cshtml"
                                                         ;
}
else if (describable is IEnumerable<IDisplayable> || describable is IEnumerable<IHasDisplayable>)
{
    var d = describable as IEnumerable<IDescribable>;
    for (int i = 0; i < d.Count(); i++)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 10764), Tuple.Create("\"", 10819)

#line 208 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 10771), Tuple.Create<System.Object, System.Int32>(d.ElementAt(i).GetUrl(Html.LoggedInUser(), Url)

#line default
#line hidden
, 10771), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 208 "..\..\Views\Details\Details.cshtml"
                                         WriteTo(__razor_helper_writer, d.ElementAt(i).Description(Html.LoggedInUser()));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a>\r\n");


#line 209 "..\..\Views\Details\Details.cshtml"

        if (i < d.Count() - 1)
        {
                

#line default
#line hidden

#line 212 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, " & ");


#line default
#line hidden

#line 212 "..\..\Views\Details\Details.cshtml"
                        ;
        }
    }
}
else if (describable is IDisplayable || describable is IHasDisplayable || describable is Enquiry || describable is IExtendedEnquiry)
{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        <a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 11115), Tuple.Create("\"", 11187)

#line 218 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 11122), Tuple.Create<System.Object, System.Int32>((describable as IDescribable).GetUrl(Html.LoggedInUser(), Url)

#line default
#line hidden
, 11122), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 218 "..\..\Views\Details\Details.cshtml"
                                                       WriteTo(__razor_helper_writer, (describable as IDescribable).Description(Html.LoggedInUser()));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a>\r\n");


#line 219 "..\..\Views\Details\Details.cshtml"
}
else if (describable is IEnumerable<IDescribable>)
{
    var d = describable as IEnumerable<IDescribable>;
    for (int i = 0; i < d.Count(); i++)
    {
            

#line default
#line hidden

#line 225 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, d.ElementAt(i).Description(Html.LoggedInUser()));


#line default
#line hidden

#line 225 "..\..\Views\Details\Details.cshtml"
                                                            

        if (i < d.Count() - 1)
        {
                

#line default
#line hidden

#line 229 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, " & ");


#line default
#line hidden

#line 229 "..\..\Views\Details\Details.cshtml"
                        ;
        }
    }
}
else if (describable is IDescribable)
{
        

#line default
#line hidden

#line 235 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, (describable as IDescribable).Description(Html.LoggedInUser()));


#line default
#line hidden

#line 235 "..\..\Views\Details\Details.cshtml"
                                                                         
}
else if (describable is Enum)
{
        

#line default
#line hidden

#line 239 "..\..\Views\Details\Details.cshtml"
WriteTo(__razor_helper_writer, (describable as Enum).Description());


#line default
#line hidden

#line 239 "..\..\Views\Details\Details.cshtml"
                                              
}



#line default
#line hidden
});

#line 242 "..\..\Views\Details\Details.cshtml"
}
#line default
#line hidden

        public _Views_Details_Details_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<body");

WriteLiteral(" class=\"page-header-hero\"");

WriteLiteral(">\r\n\r\n    <header");

WriteLiteral(" id=\"section-header\"");

WriteLiteral(" class=\"header-admin header-sm main-in-header\"");

WriteLiteral(" role=\"banner\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"bg-header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"overlay-gradient-radial\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"overlay-gradient-linear\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"bg-default\"");

WriteLiteral(" style=\"background-image: url(/content/img/background-desk.jpg)\"");

WriteLiteral("></div>\r\n        </div>\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Details\Details.cshtml"
   Write(Html.Partial("BackMenu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"header-content\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"title-hero\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Views\Details\Details.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Details\Details.cshtml"
                         if (Model != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                                <h1");

WriteLiteral(" class=\"ellipsis\"");

WriteLiteral(">\r\n                                    <strong>");

            
            #line 24 "..\..\Views\Details\Details.cshtml"
                                       Write(Model.ActualType().Name.DisplaySafeName());

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                                    <small");

WriteLiteral(" class=\"ellipsis\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\Details\Details.cshtml"
                                                       Write(Model.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                                </h1>\r\n                            </di" +
"v>\r\n");

WriteLiteral("                            <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"box-btn\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 31 "..\..\Views\Details\Details.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Details\Details.cshtml"
                                           var offset = 4 - (Model as IActionable)?.Actions().WithAccess(Html.LoggedInUser(), ViewContext.DbContext()).Count() - (Model is IHasSettings ? 1 : 0); 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 32 "..\..\Views\Details\Details.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Details\Details.cshtml"
                                         if (offset > 0)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1713), Tuple.Create("\"", 1751)
, Tuple.Create(Tuple.Create("", 1721), Tuple.Create("hidden-xs", 1721), true)
, Tuple.Create(Tuple.Create(" ", 1730), Tuple.Create("col-sm-", 1731), true)
            
            #line 34 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 1738), Tuple.Create<System.Object, System.Int32>(offset * 3
            
            #line default
            #line hidden
, 1738), false)
);

WriteLiteral(">&nbsp;</div>\r\n");

            
            #line 35 "..\..\Views\Details\Details.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 37 "..\..\Views\Details\Details.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Details\Details.cshtml"
                                         if (Model is IActionable && (Model as IActionable).Actions().WithAccess(Html.LoggedInUser(), ViewContext.DbContext()).Count() >= 1)
                                        {
                                            foreach (var action in (Model as IActionable).Actions().WithAccess(Html.LoggedInUser(), ViewContext.DbContext()))
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <div");

WriteLiteral(" class=\"col-xs-6 col-sm-3\"");

WriteLiteral(">\r\n                                                    <a");

WriteLiteral(" class=\"btn btn-primary ellipsis\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2403), Tuple.Create("\"", 2473)
            
            #line 42 "..\..\Views\Details\Details.cshtml"
              , Tuple.Create(Tuple.Create("", 2410), Tuple.Create<System.Object, System.Int32>(action.GetUrl(Html.LoggedInUser(), Url)
            
            #line default
            #line hidden
, 2410), false)
, Tuple.Create(Tuple.Create("", 2450), Tuple.Create("?", 2450), true)
            
            #line 42 "..\..\Views\Details\Details.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 2451), Tuple.Create<System.Object, System.Int32>(Request.QueryString
            
            #line default
            #line hidden
, 2451), false)
);

WriteLiteral(" title=\"#\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                        ");

            
            #line 43 "..\..\Views\Details\Details.cshtml"
                                                   Write(action.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                    </a>\r\n                     " +
"                           </div>\r\n");

            
            #line 46 "..\..\Views\Details\Details.cshtml"
                                            }
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 49 "..\..\Views\Details\Details.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Details\Details.cshtml"
                                         if (Model is IHasSettings)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <div");

WriteLiteral(" class=\"col-xs-12 col-sm-3\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"btn btn-info ellipsis\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3061), Tuple.Create("\"", 3124)
, Tuple.Create(Tuple.Create("", 3068), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 3068), false)
            
            #line 52 "..\..\Views\Details\Details.cshtml"
         , Tuple.Create(Tuple.Create("", 3070), Tuple.Create<System.Object, System.Int32>(Model.UrlSafeName()
            
            #line default
            #line hidden
, 3070), false)
, Tuple.Create(Tuple.Create("", 3090), Tuple.Create("/", 3090), true)
            
            #line 52 "..\..\Views\Details\Details.cshtml"
                               , Tuple.Create(Tuple.Create("", 3091), Tuple.Create<System.Object, System.Int32>((Model as IEntity).Id
            
            #line default
            #line hidden
, 3091), false)
, Tuple.Create(Tuple.Create("", 3115), Tuple.Create("/settings", 3115), true)
);

WriteLiteral(" title=\"Settings\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"icon icon-Settings\"");

WriteLiteral("></span>&nbsp;&nbsp;Settings\r\n                                                </a" +
">\r\n                                            </div>\r\n");

            
            #line 56 "..\..\Views\Details\Details.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                   " +
" <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n                                </div>\r\n                            </di" +
"v>\r\n");

            
            #line 62 "..\..\Views\Details\Details.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                                    <h1");

WriteLiteral(" class=\"ellipsis\"");

WriteLiteral(">\r\n                                                        <strong>Details Not Fo" +
"und</strong>\r\n                                                    </h1>\r\n       " +
"                                         </div>\r\n");

            
            #line 70 "..\..\Views\Details\Details.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n            </div>\r\n         " +
"   <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n        </div>\r\n    </header>\r\n\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n");

            
            #line 79 "..\..\Views\Details\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Details\Details.cshtml"
     if (Model != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <main");

WriteLiteral(" role=\"main\"");

WriteLiteral(" class=\"in-header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                    <table");

WriteLiteral(" class=\"table key-value table-striped\"");

WriteLiteral(">\r\n                        <tbody>\r\n");

            
            #line 86 "..\..\Views\Details\Details.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 86 "..\..\Views\Details\Details.cshtml"
                             foreach (var describable in Model.Details(Html.LoggedInUser()))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <th");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">");

            
            #line 89 "..\..\Views\Details\Details.cshtml"
                                                    Write(describable.Key);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                    <td");

WriteLiteral(" data-key=\"");

            
            #line 90 "..\..\Views\Details\Details.cshtml"
                                             Write(describable.Key);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 91 "..\..\Views\Details\Details.cshtml"
                                   Write(Render(describable.Value));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                </tr" +
">\r\n");

            
            #line 94 "..\..\Views\Details\Details.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\r\n                    </table>\r\n                <" +
"/div>\r\n\r\n");

            
            #line 99 "..\..\Views\Details\Details.cshtml"
                
            
            #line default
            #line hidden
            
            #line 99 "..\..\Views\Details\Details.cshtml"
                 foreach (var section in Model.Sections(Html.LoggedInUser()))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral("><h2>");

            
            #line 102 "..\..\Views\Details\Details.cshtml"
                                                   Write(section.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                        <table");

WriteLiteral(" class=\"table key-value table-striped\"");

WriteLiteral(">\r\n                            <tbody>\r\n");

            
            #line 105 "..\..\Views\Details\Details.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Details\Details.cshtml"
                                 foreach (var describable in section.Details)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <tr>\r\n                                       " +
" <th");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">");

            
            #line 108 "..\..\Views\Details\Details.cshtml"
                                                        Write(describable.Key);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                        <td");

WriteLiteral(" data-key=\"");

            
            #line 109 "..\..\Views\Details\Details.cshtml"
                                                 Write(describable.Key);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 110 "..\..\Views\Details\Details.cshtml"
                                       Write(Render(describable.Value));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </td>\r\n                                " +
"    </tr>\r\n");

            
            #line 113 "..\..\Views\Details\Details.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </tbody>\r\n                        </table>\r\n         " +
"           </div>\r\n");

            
            #line 117 "..\..\Views\Details\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"panel panel-default panel-tab hidden-xs\"");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" class=\"nav nav-pills nav-stacked\"");

WriteLiteral(">\r\n");

            
            #line 123 "..\..\Views\Details\Details.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\Details\Details.cshtml"
                                 if (Model.Lists(Html.LoggedInUser()) != null)
                                {
                                    for (var listNo = 0; listNo < Model.Lists(Html.LoggedInUser()).Count(); listNo++)
                                    {
                                        var list = Model.Lists(Html.LoggedInUser()).ElementAt(listNo);

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteAttribute("class", Tuple.Create(" class=\"", 6795), Tuple.Create("\"", 6833)
            
            #line 128 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 6803), Tuple.Create<System.Object, System.Int32>(listNo == 0 ? "active" : ""
            
            #line default
            #line hidden
, 6803), false)
);

WriteLiteral(">\r\n                                            <a");

WriteLiteral(" data-toggle=\"tab\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6901), Tuple.Create("\"", 6920)
, Tuple.Create(Tuple.Create("", 6908), Tuple.Create("#tab-", 6908), true)
            
            #line 129 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 6913), Tuple.Create<System.Object, System.Int32>(listNo
            
            #line default
            #line hidden
, 6913), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                                ");

            
            #line 130 "..\..\Views\Details\Details.cshtml"
                                           Write(list.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </a>\r\n                             " +
"           </li>\r\n");

            
            #line 133 "..\..\Views\Details\Details.cshtml"
                                    }
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n                        </div>\r\n                    </div>\r\n            " +
"        <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"tab-content tab-content-display\"");

WriteLiteral(">\r\n");

            
            #line 141 "..\..\Views\Details\Details.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 141 "..\..\Views\Details\Details.cshtml"
                             for (var listNo = 0; listNo < Model.Lists(Html.LoggedInUser()).Count(); listNo++)
                            {
                                var list = Model.Lists(Html.LoggedInUser()).ElementAt(listNo);


            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteAttribute("id", Tuple.Create(" id=\"", 7700), Tuple.Create("\"", 7716)
, Tuple.Create(Tuple.Create("", 7705), Tuple.Create("tab-", 7705), true)
            
            #line 145 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 7709), Tuple.Create<System.Object, System.Int32>(listNo
            
            #line default
            #line hidden
, 7709), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 7717), Tuple.Create("\"", 7772)
, Tuple.Create(Tuple.Create("", 7725), Tuple.Create("tab-pane", 7725), true)
, Tuple.Create(Tuple.Create(" ", 7733), Tuple.Create("fade", 7734), true)
, Tuple.Create(Tuple.Create(" ", 7738), Tuple.Create("in", 7739), true)
            
            #line 145 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create(" ", 7741), Tuple.Create<System.Object, System.Int32>(listNo == 0 ? "active" : ""
            
            #line default
            #line hidden
, 7742), false)
);

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                                            <h2>");

            
            #line 148 "..\..\Views\Details\Details.cshtml"
                                           Write(list.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                                        </div>\r\n                          " +
"              <ul");

WriteLiteral(" class=\"list-group\"");

WriteLiteral(">\r\n");

            
            #line 151 "..\..\Views\Details\Details.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 151 "..\..\Views\Details\Details.cshtml"
                                             if (list.Items == null || list.Items.Count() == 0)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <li>\r\n                           " +
"                         <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                                                        No ");

            
            #line 155 "..\..\Views\Details\Details.cshtml"
                                                      Write(list.Name.ToLower());

            
            #line default
            #line hidden
WriteLiteral(" to show\r\n                                                    </div>\r\n           " +
"                                     </li>\r\n");

            
            #line 158 "..\..\Views\Details\Details.cshtml"
                                            }
                                            else {
                                                foreach (var item in list.Items)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <li");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral(">\r\n                                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8949), Tuple.Create("\"", 8994)
            
            #line 163 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create("", 8956), Tuple.Create<System.Object, System.Int32>(item.GetUrl(Html.LoggedInUser(), Url)
            
            #line default
            #line hidden
, 8956), false)
);

WriteLiteral(" ");

            
            #line 163 "..\..\Views\Details\Details.cshtml"
                                                                                                    Write(Html.Raw(item is Attachment ? "target=\"_blank\"" : ""));

            
            #line default
            #line hidden
WriteLiteral(" class=\"panel-heading\">\r\n                                                        " +
"    <span");

WriteAttribute("class", Tuple.Create(" class=\"", 9142), Tuple.Create("\"", 9215)
, Tuple.Create(Tuple.Create("", 9150), Tuple.Create("icon", 9150), true)
            
            #line 164 "..\..\Views\Details\Details.cshtml"
, Tuple.Create(Tuple.Create(" ", 9154), Tuple.Create<System.Object, System.Int32>(Html.IconForDescribable(item)
            
            #line default
            #line hidden
, 9155), false)
, Tuple.Create(Tuple.Create(" ", 9185), Tuple.Create("pull-left", 9186), true)
, Tuple.Create(Tuple.Create(" ", 9195), Tuple.Create("icon-hero", 9196), true)
, Tuple.Create(Tuple.Create(" ", 9205), Tuple.Create("hidden-xs", 9206), true)
);

WriteLiteral("></span>\r\n                                                            <div");

WriteLiteral(" class=\"inner-content\"");

WriteLiteral(">\r\n                                                                <strong");

WriteLiteral(" class=\"ellipsis\"");

WriteLiteral(">");

            
            #line 166 "..\..\Views\Details\Details.cshtml"
                                                                                    Write(item.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                                                                <em");

WriteLiteral(" class=\"ellipsis\"");

WriteLiteral(">");

            
            #line 167 "..\..\Views\Details\Details.cshtml"
                                                                                Write(item.ActualType().Name.DisplaySafeName());

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n                                                            </div>\r\n      " +
"                                                  </a>\r\n                        " +
"                            </li>\r\n");

            
            #line 171 "..\..\Views\Details\Details.cshtml"
                                                }
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </ul>\r\n                                  " +
"  </div>\r\n                                </div>\r\n");

            
            #line 176 "..\..\Views\Details\Details.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </div>\r\n                </div" +
">\r\n            </div>\r\n        </main>\r\n");

            
            #line 182 "..\..\Views\Details\Details.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
