#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Realtair.Framework.Core.Actions;
    using Realtair.Framework.Core.Entities;
    using Realtair.Framework.Core.Interfaces;
    
    #line 1 "..\..\Views\Enquiry\Timeline.cshtml"
    using Realtair.Framework.Core.Web.Utilities;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Enquiry\Timeline.cshtml"
    using Realtair.Framework.Enquiries.Entities;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Enquiry/Timeline.cshtml")]
    public partial class _Views_Enquiry_Timeline_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Realtair.Framework.Core.Interfaces.ITimelineItem>>
    {
        public _Views_Enquiry_Timeline_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Enquiry\Timeline.cshtml"
   Layout = ""; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Enquiry\Timeline.cshtml"
   var attachmentId = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<ul");

WriteLiteral(" class=\"chat-list slimscroll p-t-30\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Views\Enquiry\Timeline.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Enquiry\Timeline.cshtml"
     foreach (var timelineItem in Model)
    {
        if (timelineItem is TimelineEvent)
        {
            var thisState = timelineItem as TimelineEvent;

            var typeString = "";
            if (thisState.Type == TimelineEvent.EventType.Progress)
            {
                typeString = "panel-success";
            }

            if (thisState.Type == TimelineEvent.EventType.Info)
            {
                typeString = "panel-info";
            }

            if (thisState.Type == TimelineEvent.EventType.Warning)
            {
                typeString = "panel-warning";
            }

            if (thisState.Type == TimelineEvent.EventType.Exception)
            {
                typeString = "panel-danger";
            }


            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1055), Tuple.Create("\"", 1127)
            
            #line 36 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 1063), Tuple.Create<System.Object, System.Int32>(thisState.UserResponsible == Html.LoggedInUser() ? "odd" : ""
            
            #line default
            #line hidden
, 1063), false)
);

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"chat-image\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" alt=\"Female\"");

WriteLiteral(" src=\"http://static.realtair.com/plugins/images/users/genu.jpg\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1320), Tuple.Create("\"", 1355)
, Tuple.Create(Tuple.Create("", 1328), Tuple.Create("chat-body", 1328), true)
, Tuple.Create(Tuple.Create(" ", 1337), Tuple.Create("panel", 1338), true)
            
            #line 40 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create(" ", 1343), Tuple.Create<System.Object, System.Int32>(typeString
            
            #line default
            #line hidden
, 1344), false)
);

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"panel-heading text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 42 "..\..\Views\Enquiry\Timeline.cshtml"
                   Write(thisState.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n\r\n");

            
            #line 45 "..\..\Views\Enquiry\Timeline.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Enquiry\Timeline.cshtml"
                     if (thisState.Details(Html.LoggedInUser()).Count() > 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"panel-wrapper collapse in\"");

WriteLiteral(" aria-expanded=\"true\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                                <ul>\r\n");

            
            #line 50 "..\..\Views\Enquiry\Timeline.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Enquiry\Timeline.cshtml"
                                     foreach (var describable in thisState.Details(Html.LoggedInUser()))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li><strong>");

            
            #line 52 "..\..\Views\Enquiry\Timeline.cshtml"
                                               Write(describable.Key);

            
            #line default
            #line hidden
WriteLiteral(":</strong> ");

            
            #line 52 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                          Write(Html.Render(Url, describable.Value));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 53 "..\..\Views\Enquiry\Timeline.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </div>\r\n");

            
            #line 57 "..\..\Views\Enquiry\Timeline.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 59 "..\..\Views\Enquiry\Timeline.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Enquiry\Timeline.cshtml"
                     if (thisState.Actions().WithAccess(Html.LoggedInUser(), ViewContext.DbContext()).Count() > 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n");

            
            #line 62 "..\..\Views\Enquiry\Timeline.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Enquiry\Timeline.cshtml"
                             foreach (var action in thisState.Actions().WithAccess(Html.LoggedInUser(), ViewContext.DbContext()))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <form");

WriteLiteral(" class=\"inline\"");

WriteAttribute("action", Tuple.Create(" action=\"", 2641), Tuple.Create("\"", 2669)
            
            #line 64 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 2650), Tuple.Create<System.Object, System.Int32>(action.GetUrl(Url)
            
            #line default
            #line hidden
, 2650), false)
);

WriteAttribute("method", Tuple.Create(" method=\"", 2670), Tuple.Create("\"", 2725)
            
            #line 64 "..\..\Views\Enquiry\Timeline.cshtml"
           , Tuple.Create(Tuple.Create("", 2679), Tuple.Create<System.Object, System.Int32>(action.Fields.Count() >= 1 ? "GET" : "POST"
            
            #line default
            #line hidden
, 2679), false)
);

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" name=\"ReturnUrl\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2802), Tuple.Create("\"", 2835)
            
            #line 65 "..\..\Views\Enquiry\Timeline.cshtml"
 , Tuple.Create(Tuple.Create("", 2810), Tuple.Create<System.Object, System.Int32>(Request.Url.AbsolutePath
            
            #line default
            #line hidden
, 2810), false)
);

WriteLiteral(" />\r\n                                    <button");

WriteLiteral(" class=\"btn btn-sm btn-default btn-rounded m-l-5 m-r-5\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">");

            
            #line 66 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                            Write(action.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                </form>\r\n");

            
            #line 68 "..\..\Views\Enquiry\Timeline.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

            
            #line 70 "..\..\Views\Enquiry\Timeline.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 72 "..\..\Views\Enquiry\Timeline.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 72 "..\..\Views\Enquiry\Timeline.cshtml"
                     if (thisState is IShowAttachments)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"file-attachment text-center panel-footer\"");

WriteLiteral(">\r\n");

            
            #line 75 "..\..\Views\Enquiry\Timeline.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Enquiry\Timeline.cshtml"
                             foreach (var attachment in (thisState as IShowAttachments).Attachments)
                            {
                                if (attachment.IsImage)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3557), Tuple.Create("\"", 3585)
            
            #line 79 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 3564), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 3564), false)
);

WriteLiteral(" class=\"gallery-item text-center\"");

WriteAttribute("id", Tuple.Create(" id=\"", 3619), Tuple.Create("\"", 3637)
            
            #line 79 "..\..\Views\Enquiry\Timeline.cshtml"
                         , Tuple.Create(Tuple.Create("", 3624), Tuple.Create<System.Object, System.Int32>(attachmentId
            
            #line default
            #line hidden
, 3624), false)
);

WriteLiteral(" itemprop=\"associatedMedia\"");

WriteLiteral(" itemscope=\"\"");

WriteLiteral(" itemtype=\"http://schema.org/ImageObject\"");

WriteLiteral(" data-pid=\"");

            
            #line 79 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                                                                                                                              Write(attachmentId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-caption=\"\"");

WriteLiteral(" data-width=\"1600\"");

WriteLiteral(" data-height=\"1200\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3844), Tuple.Create("\"", 3883)
            
            #line 80 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 3850), Tuple.Create<System.Object, System.Int32>(Html.Raw(attachment.GetUrl(100))
            
            #line default
            #line hidden
, 3850), false)
);

WriteLiteral(" style=\"width: 100px !important; height: 100px !important;\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" itemprop=\"thumbnail\"");

WriteLiteral(">\r\n                                    </a>\r\n");

            
            #line 82 "..\..\Views\Enquiry\Timeline.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4163), Tuple.Create("\"", 4191)
            
            #line 85 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 4170), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 4170), false)
);

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" src=\"https://realtair.com/Content/img/icon-pdf.png\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(">\r\n                                    </a>\r\n");

            
            #line 88 "..\..\Views\Enquiry\Timeline.cshtml"
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

            
            #line 91 "..\..\Views\Enquiry\Timeline.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </li>\r\n");

            
            #line 95 "..\..\Views\Enquiry\Timeline.cshtml"
        }
        else if (timelineItem is Message)
        {
            var thisMessage = timelineItem as Message;

            if (thisMessage.User != Html.LoggedInUser())
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <div");

WriteLiteral(" class=\"chat-image\"");

WriteLiteral("> <img");

WriteLiteral(" alt=\"Female\"");

WriteLiteral(" src=\"http://static.realtair.com/plugins/images/users/genu.jpg\"");

WriteLiteral("> </div>\r\n                    <div");

WriteLiteral(" class=\"chat-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"chat-text\"");

WriteLiteral(">\r\n                            <h4>");

            
            #line 106 "..\..\Views\Enquiry\Timeline.cshtml"
                           Write(thisMessage.User.Person.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                            <p> ");

            
            #line 107 "..\..\Views\Enquiry\Timeline.cshtml"
                           Write(Html.TextToHtml(thisMessage.Content));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n");

            
            #line 109 "..\..\Views\Enquiry\Timeline.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 109 "..\..\Views\Enquiry\Timeline.cshtml"
                             if (thisMessage.Attachments.Count > 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"file-attachment text-right m-t-10 m-b-10\"");

WriteLiteral(">\r\n");

            
            #line 112 "..\..\Views\Enquiry\Timeline.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 112 "..\..\Views\Enquiry\Timeline.cshtml"
                                     foreach (var attachment in thisMessage.Attachments)
                                    {
                                        if (attachment.IsImage)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5660), Tuple.Create("\"", 5688)
            
            #line 116 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 5667), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 5667), false)
);

WriteLiteral(" class=\"gallery-item text-center\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5722), Tuple.Create("\"", 5740)
            
            #line 116 "..\..\Views\Enquiry\Timeline.cshtml"
                                 , Tuple.Create(Tuple.Create("", 5727), Tuple.Create<System.Object, System.Int32>(attachmentId
            
            #line default
            #line hidden
, 5727), false)
);

WriteLiteral(" itemprop=\"associatedMedia\"");

WriteLiteral(" itemscope=\"\"");

WriteLiteral(" itemtype=\"http://schema.org/ImageObject\"");

WriteLiteral(" data-pid=\"");

            
            #line 116 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                                                                                                                                      Write(attachmentId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-caption=\"\"");

WriteLiteral(" data-width=\"1600\"");

WriteLiteral(" data-height=\"1200\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5955), Tuple.Create("\"", 5994)
            
            #line 117 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 5961), Tuple.Create<System.Object, System.Int32>(Html.Raw(attachment.GetUrl(100))
            
            #line default
            #line hidden
, 5961), false)
);

WriteLiteral(" class=\"img-rounded\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(">\r\n                                            </a>\r\n");

            
            #line 119 "..\..\Views\Enquiry\Timeline.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6277), Tuple.Create("\"", 6305)
            
            #line 122 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 6284), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 6284), false)
);

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" src=\"https://realtair.com/Content/img/icon-pdf.png\"");

WriteLiteral(" class=\"img-rounded\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(">\r\n                                            </a>\r\n");

            
            #line 125 "..\..\Views\Enquiry\Timeline.cshtml"
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </div>\r\n");

            
            #line 128 "..\..\Views\Enquiry\Timeline.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <b>");

            
            #line 129 "..\..\Views\Enquiry\Timeline.cshtml"
                          Write(thisMessage.TimelineDate.UTCToLocal().ToString("d MMM yyyy"));

            
            #line default
            #line hidden
WriteLiteral(" <span> - ");

            
            #line 129 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                 Write(thisMessage.TimelineDate.UTCToLocal().ToString("h:mm tt"));

            
            #line default
            #line hidden
WriteLiteral("</span></b>\r\n                        </div>\r\n                    </div>\r\n        " +
"        </li>\r\n");

            
            #line 133 "..\..\Views\Enquiry\Timeline.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"odd\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"chat-image\"");

WriteLiteral("> <img");

WriteLiteral(" alt=\"male\"");

WriteLiteral(" src=\"http://static.realtair.com/plugins/images/users/varun.jpg\"");

WriteLiteral("> </div>\r\n                    <div");

WriteLiteral(" class=\"chat-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"chat-text\"");

WriteLiteral(">\r\n                            <h4>");

            
            #line 140 "..\..\Views\Enquiry\Timeline.cshtml"
                           Write(thisMessage.User.Person.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                            <p> ");

            
            #line 141 "..\..\Views\Enquiry\Timeline.cshtml"
                           Write(Html.TextToHtml(thisMessage.Content));

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n");

            
            #line 142 "..\..\Views\Enquiry\Timeline.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 142 "..\..\Views\Enquiry\Timeline.cshtml"
                             if (thisMessage.Attachments.Count > 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"file-attachment text-right m-t-10 m-b-5\"");

WriteLiteral(">\r\n");

            
            #line 145 "..\..\Views\Enquiry\Timeline.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 145 "..\..\Views\Enquiry\Timeline.cshtml"
                                     foreach (var attachment in thisMessage.Attachments)
                                    {
                                        if (attachment.IsImage)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 7914), Tuple.Create("\"", 7942)
            
            #line 149 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 7921), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 7921), false)
);

WriteLiteral(" class=\"gallery-item text-center\"");

WriteAttribute("id", Tuple.Create(" id=\"", 7976), Tuple.Create("\"", 7994)
            
            #line 149 "..\..\Views\Enquiry\Timeline.cshtml"
                                 , Tuple.Create(Tuple.Create("", 7981), Tuple.Create<System.Object, System.Int32>(attachmentId
            
            #line default
            #line hidden
, 7981), false)
);

WriteLiteral(" itemprop=\"associatedMedia\"");

WriteLiteral(" itemscope=\"\"");

WriteLiteral(" itemtype=\"http://schema.org/ImageObject\"");

WriteLiteral(" data-pid=\"");

            
            #line 149 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                                                                                                                                      Write(attachmentId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-caption=\"\"");

WriteLiteral(" data-width=\"1600\"");

WriteLiteral(" data-height=\"1200\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 8209), Tuple.Create("\"", 8248)
            
            #line 150 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 8215), Tuple.Create<System.Object, System.Int32>(Html.Raw(attachment.GetUrl(100))
            
            #line default
            #line hidden
, 8215), false)
);

WriteLiteral(" class=\"img-rounded\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(">\r\n                                            </a>\r\n");

            
            #line 152 "..\..\Views\Enquiry\Timeline.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8531), Tuple.Create("\"", 8559)
            
            #line 155 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 8538), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 8538), false)
);

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                                <img");

WriteLiteral(" src=\"https://realtair.com/Content/img/icon-pdf.png\"");

WriteLiteral(" class=\"img-rounded\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(">\r\n                                            </a>\r\n");

            
            #line 158 "..\..\Views\Enquiry\Timeline.cshtml"
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </div>\r\n");

            
            #line 161 "..\..\Views\Enquiry\Timeline.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <b>");

            
            #line 162 "..\..\Views\Enquiry\Timeline.cshtml"
                          Write(thisMessage.TimelineDate.UTCToLocal().ToString("d MMM yyyy"));

            
            #line default
            #line hidden
WriteLiteral(" <span> - ");

            
            #line 162 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                 Write(thisMessage.TimelineDate.UTCToLocal().ToString("h:mm tt"));

            
            #line default
            #line hidden
WriteLiteral("</span></b>\r\n                        </div>\r\n                    </div>\r\n        " +
"        </li>\r\n");

            
            #line 166 "..\..\Views\Enquiry\Timeline.cshtml"
            }
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>");

        }
    }
}
#pragma warning restore 1591
