#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Realtair.Framework.Core.Actions;
    using Realtair.Framework.Core.Entities;
    using Realtair.Framework.Core.Interfaces;
    
    #line 1 "..\..\Views\Enquiry\Timeline.cshtml"
    using Realtair.Framework.Core.Web.Utilities;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Enquiry\Timeline.cshtml"
    using Realtair.Framework.Enquiries.Entities;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Enquiry/Timeline.cshtml")]
    public partial class _Views_Enquiry_Timeline_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Realtair.Framework.Core.Interfaces.ITimelineItem>>
    {
        public _Views_Enquiry_Timeline_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Enquiry\Timeline.cshtml"
   Layout = ""; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Enquiry\Timeline.cshtml"
   var attachmentId = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<ul");

WriteLiteral(" class=\"chat-list slimscroll p-t-30\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Views\Enquiry\Timeline.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Enquiry\Timeline.cshtml"
     foreach (var timelineItem in Model)
    {
        if (timelineItem is TimelineEvent)
        {
            var thisState = timelineItem as TimelineEvent;

            var typeString = "";
            if (thisState.Type == TimelineEvent.EventType.Progress)
            {
                typeString = "panel-success";
            }

            if (thisState.Type == TimelineEvent.EventType.Info)
            {
                typeString = "panel-info";
            }

            if (thisState.Type == TimelineEvent.EventType.Warning)
            {
                typeString = "panel-warning";
            }

            if (thisState.Type == TimelineEvent.EventType.Exception)
            {
                typeString = "panel-danger";
            }


            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1055), Tuple.Create("\"", 1127)
            
            #line 36 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 1063), Tuple.Create<System.Object, System.Int32>(thisState.UserResponsible == Html.LoggedInUser() ? "odd" : ""
            
            #line default
            #line hidden
, 1063), false)
);

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"chat-image\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"img-circle\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Enquiry\Timeline.cshtml"
                                         Write(thisState.UserResponsible.Person.Initials);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </div>\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 1315), Tuple.Create("\"", 1350)
, Tuple.Create(Tuple.Create("", 1323), Tuple.Create("chat-body", 1323), true)
, Tuple.Create(Tuple.Create(" ", 1332), Tuple.Create("panel", 1333), true)
            
            #line 40 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create(" ", 1338), Tuple.Create<System.Object, System.Int32>(typeString
            
            #line default
            #line hidden
, 1339), false)
);

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"panel-heading text-center\"");

WriteLiteral(">\r\n                        <p>");

            
            #line 42 "..\..\Views\Enquiry\Timeline.cshtml"
                      Write(thisState.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </div>\r\n\r\n");

            
            #line 45 "..\..\Views\Enquiry\Timeline.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\Enquiry\Timeline.cshtml"
                     if (thisState.Details(Html.LoggedInUser()).Count() > 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                            <ul>\r\n");

            
            #line 49 "..\..\Views\Enquiry\Timeline.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Enquiry\Timeline.cshtml"
                                 foreach (var describable in thisState.Details(Html.LoggedInUser()))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li><strong>");

            
            #line 51 "..\..\Views\Enquiry\Timeline.cshtml"
                                           Write(describable.Key);

            
            #line default
            #line hidden
WriteLiteral(":</strong> ");

            
            #line 51 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                      Write(Html.Render(Url, describable.Value));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 52 "..\..\Views\Enquiry\Timeline.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n                        </div>\r\n");

            
            #line 55 "..\..\Views\Enquiry\Timeline.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 57 "..\..\Views\Enquiry\Timeline.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Enquiry\Timeline.cshtml"
                     if (thisState.Actions().WithAccess(Html.LoggedInUser(), ViewContext.DbContext()).Count() > 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n");

            
            #line 60 "..\..\Views\Enquiry\Timeline.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\Enquiry\Timeline.cshtml"
                             foreach (var action in thisState.Actions().WithAccess(Html.LoggedInUser(), ViewContext.DbContext()))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <form");

WriteLiteral(" class=\"inline\"");

WriteAttribute("action", Tuple.Create(" action=\"", 2491), Tuple.Create("\"", 2519)
            
            #line 62 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 2500), Tuple.Create<System.Object, System.Int32>(action.GetUrl(Url)
            
            #line default
            #line hidden
, 2500), false)
);

WriteAttribute("method", Tuple.Create(" method=\"", 2520), Tuple.Create("\"", 2575)
            
            #line 62 "..\..\Views\Enquiry\Timeline.cshtml"
           , Tuple.Create(Tuple.Create("", 2529), Tuple.Create<System.Object, System.Int32>(action.Fields.Count() >= 1 ? "GET" : "POST"
            
            #line default
            #line hidden
, 2529), false)
);

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" name=\"ReturnUrl\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2652), Tuple.Create("\"", 2696)
            
            #line 63 "..\..\Views\Enquiry\Timeline.cshtml"
 , Tuple.Create(Tuple.Create("", 2660), Tuple.Create<System.Object, System.Int32>(thisState.ParentEnquiry.GetUrl(Url)
            
            #line default
            #line hidden
, 2660), false)
);

WriteLiteral(" />\r\n                                    <button");

WriteLiteral(" class=\"btn btn-sm btn-default btn-rounded m-l-5 m-r-5\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">");

            
            #line 64 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                            Write(action.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                </form>\r\n");

            
            #line 66 "..\..\Views\Enquiry\Timeline.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

            
            #line 68 "..\..\Views\Enquiry\Timeline.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 70 "..\..\Views\Enquiry\Timeline.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Enquiry\Timeline.cshtml"
                     if (thisState is IShowAttachments && (thisState as IShowAttachments).Attachments != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"file-attachment text-center panel-body\"");

WriteLiteral(">\r\n");

            
            #line 73 "..\..\Views\Enquiry\Timeline.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 73 "..\..\Views\Enquiry\Timeline.cshtml"
                             foreach (var attachment in (thisState as IShowAttachments).Attachments)
                            {
                                if (attachment.IsImage)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3471), Tuple.Create("\"", 3499)
            
            #line 77 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 3478), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 3478), false)
);

WriteLiteral(" class=\"gallery-item text-center\"");

WriteAttribute("id", Tuple.Create(" id=\"", 3533), Tuple.Create("\"", 3551)
            
            #line 77 "..\..\Views\Enquiry\Timeline.cshtml"
                         , Tuple.Create(Tuple.Create("", 3538), Tuple.Create<System.Object, System.Int32>(attachmentId
            
            #line default
            #line hidden
, 3538), false)
);

WriteLiteral(" itemprop=\"associatedMedia\"");

WriteLiteral(" itemscope=\"\"");

WriteLiteral(" itemtype=\"http://schema.org/ImageObject\"");

WriteLiteral(" data-pid=\"");

            
            #line 77 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                                                                                                                              Write(attachmentId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-caption=\"\"");

WriteLiteral(" data-width=\"1600\"");

WriteLiteral(" data-height=\"1200\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3758), Tuple.Create("\"", 3797)
            
            #line 78 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 3764), Tuple.Create<System.Object, System.Int32>(Html.Raw(attachment.GetUrl(100))
            
            #line default
            #line hidden
, 3764), false)
);

WriteLiteral(" style=\"width: 100px !important; height: 100px !important;\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" itemprop=\"thumbnail\"");

WriteLiteral(">\r\n                                    </a>\r\n");

            
            #line 80 "..\..\Views\Enquiry\Timeline.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4077), Tuple.Create("\"", 4105)
            
            #line 83 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 4084), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 4084), false)
);

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4189), Tuple.Create("\"", 4219)
            
            #line 84 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 4195), Tuple.Create<System.Object, System.Int32>(attachment.ThumbnailUrl
            
            #line default
            #line hidden
, 4195), false)
);

WriteLiteral(" alt=\"#\"");

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(">\r\n                                    </a>\r\n");

            
            #line 86 "..\..\Views\Enquiry\Timeline.cshtml"
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n");

            
            #line 89 "..\..\Views\Enquiry\Timeline.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                        <b");

WriteLiteral(" class=\"time\"");

WriteLiteral(">");

            
            #line 92 "..\..\Views\Enquiry\Timeline.cshtml"
                                   Write(thisState.TimelineDate.UTCToLocal().ToString("d MMM yyyy"));

            
            #line default
            #line hidden
WriteLiteral(" <span> - ");

            
            #line 92 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                        Write(thisState.TimelineDate.UTCToLocal().ToString("h:mm tt"));

            
            #line default
            #line hidden
WriteLiteral("</span></b>\r\n                    </div>\r\n                </div>\r\n            </li" +
">\r\n");

            
            #line 96 "..\..\Views\Enquiry\Timeline.cshtml"
        }
        else if (timelineItem is Message)
        {
            var thisMessage = timelineItem as Message;

            if (thisMessage.User != Html.LoggedInUser())
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <div");

WriteLiteral(" class=\"chat-image\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"img-circle\"");

WriteLiteral(">");

            
            #line 104 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                  Write(thisMessage.User.Person.Initials);

            
            #line default
            #line hidden
WriteLiteral("</span> </div>\r\n                    <div");

WriteLiteral(" class=\"chat-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"chat-text\"");

WriteLiteral(">\r\n                            <h4>");

            
            #line 107 "..\..\Views\Enquiry\Timeline.cshtml"
                           Write(thisMessage.User.Person.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                            <p> ");

            
            #line 108 "..\..\Views\Enquiry\Timeline.cshtml"
                           Write(Html.TextToHtml(thisMessage.Content));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n");

            
            #line 110 "..\..\Views\Enquiry\Timeline.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 110 "..\..\Views\Enquiry\Timeline.cshtml"
                             if (thisMessage.Attachments.Count > 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"file-attachment text-right m-t-10 m-b-10\"");

WriteLiteral(">\r\n");

            
            #line 113 "..\..\Views\Enquiry\Timeline.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 113 "..\..\Views\Enquiry\Timeline.cshtml"
                                     foreach (var attachment in thisMessage.Attachments)
                                    {
                                        if (attachment.IsImage)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5793), Tuple.Create("\"", 5821)
            
            #line 117 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 5800), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 5800), false)
);

WriteLiteral(" class=\"gallery-item text-center\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5855), Tuple.Create("\"", 5873)
            
            #line 117 "..\..\Views\Enquiry\Timeline.cshtml"
                                 , Tuple.Create(Tuple.Create("", 5860), Tuple.Create<System.Object, System.Int32>(attachmentId
            
            #line default
            #line hidden
, 5860), false)
);

WriteLiteral(" itemprop=\"associatedMedia\"");

WriteLiteral(" itemscope=\"\"");

WriteLiteral(" itemtype=\"http://schema.org/ImageObject\"");

WriteLiteral(" data-pid=\"");

            
            #line 117 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                                                                                                                                      Write(attachmentId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-caption=\"\"");

WriteLiteral(" data-width=\"1600\"");

WriteLiteral(" data-height=\"1200\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6088), Tuple.Create("\"", 6127)
            
            #line 118 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 6094), Tuple.Create<System.Object, System.Int32>(Html.Raw(attachment.GetUrl(100))
            
            #line default
            #line hidden
, 6094), false)
);

WriteLiteral(" class=\"img-rounded\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(">\r\n                                            </a>\r\n");

            
            #line 120 "..\..\Views\Enquiry\Timeline.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6410), Tuple.Create("\"", 6438)
            
            #line 123 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 6417), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 6417), false)
);

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6530), Tuple.Create("\"", 6560)
            
            #line 124 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 6536), Tuple.Create<System.Object, System.Int32>(attachment.ThumbnailUrl
            
            #line default
            #line hidden
, 6536), false)
);

WriteLiteral(" class=\"img-rounded\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(">\r\n                                            </a>\r\n");

            
            #line 126 "..\..\Views\Enquiry\Timeline.cshtml"
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </div>\r\n");

            
            #line 129 "..\..\Views\Enquiry\Timeline.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <b>");

            
            #line 130 "..\..\Views\Enquiry\Timeline.cshtml"
                          Write(thisMessage.TimelineDate.UTCToLocal().ToString("d MMM yyyy"));

            
            #line default
            #line hidden
WriteLiteral(" <span> - ");

            
            #line 130 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                 Write(thisMessage.TimelineDate.UTCToLocal().ToString("h:mm tt"));

            
            #line default
            #line hidden
WriteLiteral("</span></b>\r\n                        </div>\r\n                    </div>\r\n        " +
"        </li>\r\n");

            
            #line 134 "..\..\Views\Enquiry\Timeline.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"odd\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"chat-image\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"img-circle\"");

WriteLiteral(">");

            
            #line 138 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                  Write(thisMessage.User.Person.Initials);

            
            #line default
            #line hidden
WriteLiteral("</span> </div>\r\n                    <div");

WriteLiteral(" class=\"chat-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"chat-text\"");

WriteLiteral(">\r\n                            <h4>");

            
            #line 141 "..\..\Views\Enquiry\Timeline.cshtml"
                           Write(thisMessage.User.Person.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                            <p> ");

            
            #line 142 "..\..\Views\Enquiry\Timeline.cshtml"
                           Write(Html.TextToHtml(thisMessage.Content));

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n");

            
            #line 143 "..\..\Views\Enquiry\Timeline.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 143 "..\..\Views\Enquiry\Timeline.cshtml"
                             if (thisMessage.Attachments.Count > 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"gallery file-attachment text-right m-t-10 m-b-5\"");

WriteLiteral(">\r\n");

            
            #line 146 "..\..\Views\Enquiry\Timeline.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 146 "..\..\Views\Enquiry\Timeline.cshtml"
                                     foreach (var attachment in thisMessage.Attachments)
                                    {
                                        if (attachment.IsImage)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <figure");

WriteLiteral(" itemprop=\"associatedMedia\"");

WriteLiteral(" itemscope");

WriteLiteral(" itemtype=\"http://schema.org/ImageObject\"");

WriteLiteral(">\r\n                                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8157), Tuple.Create("\"", 8185)
            
            #line 151 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 8164), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 8164), false)
);

WriteLiteral(" class=\"gallery-item text-center\"");

WriteAttribute("id", Tuple.Create(" id=\"", 8219), Tuple.Create("\"", 8237)
            
            #line 151 "..\..\Views\Enquiry\Timeline.cshtml"
                                     , Tuple.Create(Tuple.Create("", 8224), Tuple.Create<System.Object, System.Int32>(attachmentId
            
            #line default
            #line hidden
, 8224), false)
);

WriteLiteral(" itemprop=\"associatedMedia\"");

WriteLiteral(" itemscope=\"\"");

WriteLiteral(" itemtype=\"http://schema.org/ImageObject\"");

WriteLiteral(" data-pid=\"");

            
            #line 151 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                                                                                                                                          Write(attachmentId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-caption=\"\"");

WriteLiteral(" data-width=\"1600\"");

WriteLiteral(" data-height=\"1200\"");

WriteLiteral(">\r\n                                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 8456), Tuple.Create("\"", 8495)
            
            #line 152 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 8462), Tuple.Create<System.Object, System.Int32>(Html.Raw(attachment.GetUrl(100))
            
            #line default
            #line hidden
, 8462), false)
);

WriteLiteral(" class=\"img-rounded\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(">\r\n                                                </a>\r\n                        " +
"                    </figure>\r\n");

            
            #line 155 "..\..\Views\Enquiry\Timeline.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <figure");

WriteLiteral(" itemprop=\"associatedMedia\"");

WriteLiteral(" itemscope");

WriteLiteral(" itemtype=\"http://schema.org/ImageObject\"");

WriteLiteral(">\r\n                                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8973), Tuple.Create("\"", 9001)
            
            #line 159 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 8980), Tuple.Create<System.Object, System.Int32>(attachment.GetUrl(0)
            
            #line default
            #line hidden
, 8980), false)
);

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 9097), Tuple.Create("\"", 9127)
            
            #line 160 "..\..\Views\Enquiry\Timeline.cshtml"
, Tuple.Create(Tuple.Create("", 9103), Tuple.Create<System.Object, System.Int32>(attachment.ThumbnailUrl
            
            #line default
            #line hidden
, 9103), false)
);

WriteLiteral(" class=\"img-rounded\"");

WriteLiteral(" alt=\"#\"");

WriteLiteral(" width=\"80\"");

WriteLiteral(" height=\"80\"");

WriteLiteral(">\r\n                                                </a>\r\n                        " +
"                    </figure>\r\n");

            
            #line 163 "..\..\Views\Enquiry\Timeline.cshtml"
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </div>\r\n");

            
            #line 166 "..\..\Views\Enquiry\Timeline.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <b>");

            
            #line 167 "..\..\Views\Enquiry\Timeline.cshtml"
                          Write(thisMessage.TimelineDate.UTCToLocal().ToString("d MMM yyyy"));

            
            #line default
            #line hidden
WriteLiteral(" <span> - ");

            
            #line 167 "..\..\Views\Enquiry\Timeline.cshtml"
                                                                                                 Write(thisMessage.TimelineDate.UTCToLocal().ToString("h:mm tt"));

            
            #line default
            #line hidden
WriteLiteral("</span></b>\r\n                        </div>\r\n                    </div>\r\n        " +
"        </li>\r\n");

            
            #line 171 "..\..\Views\Enquiry\Timeline.cshtml"
            }
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n\r\n<script");

WriteLiteral(" src=\"https://static.realtair.com/js/gallery.js\"");

WriteLiteral("></script>");

        }
    }
}
#pragma warning restore 1591
