#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Realtair.Framework.Core.Actions;
    
    #line 1 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
    using Realtair.Framework.Core.Data;
    
    #line default
    #line hidden
    using Realtair.Framework.Core.Entities;
    using Realtair.Framework.Core.Interfaces;
    using Realtair.Framework.Core.Web.Utilities;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Fields/Settings/_StatusField.cshtml")]
    public partial class _Views_Shared_Fields_Settings__StatusField_cshtml : System.Web.Mvc.WebViewPage<Realtair.Framework.Core.Actions.Field>
    {
        public _Views_Shared_Fields_Settings__StatusField_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
  
    var attribute = Model.FieldAttribute as Realtair.Framework.Core.Actions.FieldAttributes.StatusFieldAttribute;
    var options = attribute.Options(Model.Action, Html.LoggedInUser());
    var hopefullyUniqueId = Math.Abs(Model.GetHashCode());
    var taskRecord = Model.Value as Realtair.Framework.Enquiries.Entities.TaskRecord;    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-3 col-sm-4\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
                                Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"col-md-9 col-sm-8\"");

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
         if (options.Count() == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <select");

WriteAttribute("id", Tuple.Create(" id=\"", 672), Tuple.Create("\"", 695)
            
            #line 19 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
, Tuple.Create(Tuple.Create("", 677), Tuple.Create<System.Object, System.Int32>(hopefullyUniqueId
            
            #line default
            #line hidden
, 677), false)
);

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" disabled>\r\n                <option>None to display</option>\r\n            </selec" +
"t>\r\n");

            
            #line 22 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <select");

WriteAttribute("id", Tuple.Create(" id=\"", 857), Tuple.Create("\"", 880)
            
            #line 25 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
, Tuple.Create(Tuple.Create("", 862), Tuple.Create<System.Object, System.Int32>(hopefullyUniqueId
            
            #line default
            #line hidden
, 862), false)
);

WriteLiteral(" class=\"form-control\"");

WriteAttribute("name", Tuple.Create(" name=\"", 902), Tuple.Create("\"", 933)
            
            #line 25 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
, Tuple.Create(Tuple.Create("", 909), Tuple.Create<System.Object, System.Int32>(Model.PropertyInfo.Name
            
            #line default
            #line hidden
, 909), false)
);

WriteLiteral(">\r\n");

            
            #line 26 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
                
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
                 foreach (var option in options)
                {                    

            
            #line default
            #line hidden
WriteLiteral("                    <option ");

            
            #line 28 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
                        Write(option.Id.ToString() == taskRecord.GetStatusId(SingletonDbContext.Db).ToString() ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(" value=\"");

            
            #line 28 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
                                                                                                                                    Write(option.Id.ToString());

            
            #line default
            #line hidden
WriteLiteral("\">");

            
            #line 28 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
                                                                                                                                                           Write(option.Description);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 29 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </select>\r\n");

            
            #line 31 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" href=\"https://static.realtair.com/plugins/select2/css/select2.min.css\"");

WriteLiteral(">\r\n        <script");

WriteLiteral(" src=\"https://static.realtair.com/plugins/select2/js/select2.min.js\"");

WriteLiteral("></script>\r\n        <script>\r\n            $(window).resize(function () {\r\n       " +
"         $(\'.select2\').css(\'width\', \"100%\");\r\n            });\r\n\r\n            $(\'" +
"#");

            
            #line 40 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
            Write(hopefullyUniqueId);

            
            #line default
            #line hidden
WriteLiteral("\').select2();\r\n\r\n            $(\'#");

            
            #line 42 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
           Write(hopefullyUniqueId);

            
            #line default
            #line hidden
WriteLiteral("\').change(function () {\r\n                $.post(window.location.origin+\"/task-rec" +
"ord/");

            
            #line 43 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
                                                        Write(taskRecord.Id);

            
            #line default
            #line hidden
WriteLiteral("/run/update-task-status\", { \"status\": $(\"#");

            
            #line 43 "..\..\Views\Shared\Fields\Settings\_StatusField.cshtml"
                                                                                                                 Write(hopefullyUniqueId);

            
            #line default
            #line hidden
WriteLiteral("\").val() }, function (data) { });\r\n            });\r\n        </script>\r\n    </div>" +
"\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
