#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    
    #line 9 "..\..\Views\Actions\Action.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    
    #line 8 "..\..\Views\Actions\Action.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Actions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Entities;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Interfaces;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Web.Utilities;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Enquiries.Entities;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Enquiries.Interfaces;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Actions/Action.cshtml")]
    public partial class _Views_Actions_Action_cshtml : System.Web.Mvc.WebViewPage<Realtair.Framework.Core.Web.Controllers.ActionsController.ActionViewModel>
    {
        public _Views_Actions_Action_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Actions\Action.cshtml"
  
    var detailsTemplate = "-";
    var cancelActionUrl = "";

    if (Request.QueryString["ReturnUrl"] != null)
    {
        cancelActionUrl = Request.QueryString["ReturnUrl"].ToString();
    }

    if (Model.Action.This != null)
    {
        detailsTemplate = $"{Model.Action.This.ActualType().Name}/{Model.Action.GetType().Name}";
    }

    if (Html.ViewExists(detailsTemplate))
    {
        Layout = null;
        Html.RenderPartial(detailsTemplate, Model.Action);
    }
    else
    {
        IEnumerable<Field> shown;
        IEnumerable<Field> shownWithFieldSets;
        IEnumerable<Field> hidden;

        TempData["ShowSubmit"] = true;

        if (Model.IsMultiPage)
        {
            shown = Model.FieldsForPage;
            shownWithFieldSets = Model.FieldsForPage.Where(f => f.FieldSetAttribute != null).ToList();
            hidden = Model.HiddenFieldsForPage;
        }
        else
        {
            shown = Model.Fields;
            shownWithFieldSets = Model.Fields.Where(f => f.FieldSetAttribute != null).ToList();
            hidden = null;
        }





            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"content bg-grey-lt\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("            ");

            
            #line 56 "..\..\Views\Actions\Action.cshtml"
       Write(Html.Partial("FlowerHorn/MobileNavigation"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" id=\"page-wrapper\"");

WriteLiteral(" class=\"padding-sides-sm pad-form-mob\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" id=\"loader-wrapper\"");

WriteLiteral(" class=\"hide-bg\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"loader\"");

WriteLiteral("></div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-sm-10 col-sm-offset-1\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                        <h2>\r\n");

            
            #line 67 "..\..\Views\Actions\Action.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Actions\Action.cshtml"
                             if (Model.IsMultiPage)
                            {
                                
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Actions\Action.cshtml"
                           Write(Model.Page.Name.ToUpper());

            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Actions\Action.cshtml"
                                                          
                            }
                            else
                            {
                                
            
            #line default
            #line hidden
            
            #line 73 "..\..\Views\Actions\Action.cshtml"
                           Write(Model.Action.Description(Html.LoggedInUser()).ToUpper());

            
            #line default
            #line hidden
            
            #line 73 "..\..\Views\Actions\Action.cshtml"
                                                                                        
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </h2>\r\n\r\n");

            
            #line 77 "..\..\Views\Actions\Action.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\Actions\Action.cshtml"
                          
                            var parentEnquiry = (Model.Action.This as IHasParentEnquiry)?.ParentEnquiry;
                            if (parentEnquiry != null)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <h3");

WriteLiteral(" class=\"no-margin-tb\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-home\"");

WriteLiteral("></i> ");

            
            #line 82 "..\..\Views\Actions\Action.cshtml"
                                                           Write(parentEnquiry.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </h3>\r\n");

WriteLiteral("                                <br />\r\n");

            
            #line 85 "..\..\Views\Actions\Action.cshtml"
                            }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        ");

WriteLiteral("\r\n");

            
            #line 89 "..\..\Views\Actions\Action.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Actions\Action.cshtml"
                         if (Model.Action.HasValidated && !Model.Action.IsValid)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" style=\"padding: 0;\"");

WriteLiteral(">\r\n");

            
            #line 92 "..\..\Views\Actions\Action.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\Actions\Action.cshtml"
                                 foreach (var error in Model.Action.Errors.Where(e => e.MemberNames.Count() == 0))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">");

            
            #line 94 "..\..\Views\Actions\Action.cshtml"
                                                               Write(error.ErrorMessage);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 95 "..\..\Views\Actions\Action.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n");

            
            #line 97 "..\..\Views\Actions\Action.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <form");

WriteLiteral(" class=\"form-horizontal panel panel-body form-padding\"");

WriteLiteral(" id=\"main-form\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

            
            #line 137 "..\..\Views\Actions\Action.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 137 "..\..\Views\Actions\Action.cshtml"
                                     foreach (var field in shown)
                                    {
                                        if (field.FieldSetAttribute != null)
                                        {
                                            var fieldSetItems = shownWithFieldSets.Where(s => s.FieldSetAttribute.Legend == field.FieldSetAttribute.Legend).ToList();
                                            if (fieldSetItems.Any())
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <fieldset");

WriteAttribute("class", Tuple.Create(" class=\"", 6908), Tuple.Create("\"", 7061)
            
            #line 144 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 6916), Tuple.Create<System.Object, System.Int32>(shownWithFieldSets.First().UniqueName == shown.First().UniqueName && fieldSetItems.First().UniqueName == field.UniqueName ? "" : "margin-t-md"
            
            #line default
            #line hidden
, 6916), false)
);

WriteLiteral(">\r\n                                                    <legend>");

            
            #line 145 "..\..\Views\Actions\Action.cshtml"
                                                       Write(field.FieldSetAttribute.Legend);

            
            #line default
            #line hidden
WriteLiteral("</legend>\r\n                                                    <div");

WriteLiteral(" class=\"p-l-30\"");

WriteLiteral(">\r\n");

            
            #line 147 "..\..\Views\Actions\Action.cshtml"
                                                        
            
            #line default
            #line hidden
            
            #line 147 "..\..\Views\Actions\Action.cshtml"
                                                         foreach (var item in fieldSetItems)
                                                        {
                                                            var fieldWithReturnType = $"Fields/_{item.PropertyType.Name}_{item.FieldAttribute.GetType().Name.Substring(0, item.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                                            var fieldWithoutReturnType = $"Fields/_{item.FieldAttribute.GetType().Name.Substring(0, item.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                                            var fieldThatWorksForBoth = $"Fields/_{item.PropertyType.Name}_Field";

                                                            if (Html.ViewExists(fieldWithReturnType))
                                                            {
                                                                Html.RenderPartial(fieldWithReturnType, item);
                                                            }
                                                            else if (Html.ViewExists(fieldWithoutReturnType))
                                                            {
                                                                Html.RenderPartial(fieldWithoutReturnType, item);
                                                            }
                                                            else if (Html.ViewExists(fieldThatWorksForBoth))
                                                            {
                                                                Html.RenderPartial(fieldThatWorksForBoth, item);
                                                            }
                                                            else
                                                            {


            
            #line default
            #line hidden
WriteLiteral("                                                                <p> Cannot render" +
" field view, looked for both ");

            
            #line 168 "..\..\Views\Actions\Action.cshtml"
                                                                                                         Write(fieldWithReturnType);

            
            #line default
            #line hidden
WriteLiteral(" and ");

            
            #line 168 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                  Write(fieldWithoutReturnType);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n");

            
            #line 169 "..\..\Views\Actions\Action.cshtml"

                                                            }
                                                        }

            
            #line default
            #line hidden
WriteLiteral("                                                    </div>\r\n                     " +
"                           </fieldset>");

            
            #line 173 "..\..\Views\Actions\Action.cshtml"
                                                           shownWithFieldSets = shownWithFieldSets.Except(fieldSetItems).ToList();
                                            }
                                        }
                                        else
                                        {
                                            var fieldWithReturnType = $"Fields/_{field.PropertyType.Name}_{field.FieldAttribute.GetType().Name.Substring(0, field.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                            var fieldWithoutReturnType = $"Fields/_{field.FieldAttribute.GetType().Name.Substring(0, field.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                            var fieldThatWorksForBoth = $"Fields/_{field.PropertyType.Name}_Field";

                                            if (Html.ViewExists(fieldWithReturnType))
                                            {
                                                Html.RenderPartial(fieldWithReturnType, field);
                                            }
                                            else if (Html.ViewExists(fieldWithoutReturnType))
                                            {
                                                Html.RenderPartial(fieldWithoutReturnType, field);
                                            }
                                            else if (Html.ViewExists(fieldThatWorksForBoth))
                                            {
                                                Html.RenderPartial(fieldThatWorksForBoth, field);
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <p>Cannot render field view, look" +
"ed for both ");

            
            #line 196 "..\..\Views\Actions\Action.cshtml"
                                                                                        Write(fieldWithReturnType);

            
            #line default
            #line hidden
WriteLiteral(" and ");

            
            #line 196 "..\..\Views\Actions\Action.cshtml"
                                                                                                                 Write(fieldWithoutReturnType);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 197 "..\..\Views\Actions\Action.cshtml"
                                            }
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 201 "..\..\Views\Actions\Action.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 201 "..\..\Views\Actions\Action.cshtml"
                                     if (hidden != null)
                                    {
                                        foreach (var field in hidden)
                                        {
                                            if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.BulkFileUploadFieldAttribute && field.Value is IEnumerable<Attachment>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 12110), Tuple.Create("\"", 12134)
            
            #line 207 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 12117), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 12117), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 12135), Tuple.Create("\"", 12221)
, Tuple.Create(Tuple.Create("", 12143), Tuple.Create("[", 12143), true)
, Tuple.Create(Tuple.Create("", 12144), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 207 "..\..\Views\Actions\Action.cshtml"
                                                                                                       foreach (var a in field.Value as IEnumerable<Attachment>) { 
            
            #line default
            #line hidden
            
            #line 207 "..\..\Views\Actions\Action.cshtml"
                                                                                                                             WriteTo(__razor_attribute_value_writer, a.Id + ",");

            
            #line default
            #line hidden
            
            #line 207 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                 }
            
            #line default
            #line hidden
}), 12144), false)
, Tuple.Create(Tuple.Create("", 12220), Tuple.Create("]", 12220), true)
);

WriteLiteral(" />\r\n");

            
            #line 208 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IList<Attachment>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 12477), Tuple.Create("\"", 12501)
            
            #line 211 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 12484), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 12484), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 12502), Tuple.Create("\"", 12593)
, Tuple.Create(Tuple.Create("", 12510), Tuple.Create("[", 12510), true)
            
            #line 211 "..\..\Views\Actions\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 12511), Tuple.Create<System.Object, System.Int32>(string.Join(",",((IList<Attachment>)field.Value).Select(f => f.Id.ToString()))
            
            #line default
            #line hidden
, 12511), false)
, Tuple.Create(Tuple.Create("", 12592), Tuple.Create("]", 12592), true)
);

WriteLiteral(" />\r\n");

            
            #line 212 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is ICustomViewModel)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 12848), Tuple.Create("\"", 12872)
            
            #line 215 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 12855), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 12855), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 12873), Tuple.Create("\"", 12929)
            
            #line 215 "..\..\Views\Actions\Action.cshtml"
                     , Tuple.Create(Tuple.Create("", 12881), Tuple.Create<System.Object, System.Int32>((field.Value as ICustomViewModel).Serialize()
            
            #line default
            #line hidden
, 12881), false)
);

WriteLiteral(" />\r\n");

            
            #line 216 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<ICustomViewModel>)
                                            {
                                                if ((field.Value as IEnumerable<ICustomViewModel>).Count() > 0)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 13365), Tuple.Create("\"", 13389)
            
            #line 221 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 13372), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 13372), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 13390), Tuple.Create("\"", 13494)
, Tuple.Create(Tuple.Create("", 13398), Tuple.Create("[", 13398), true)
            
            #line 221 "..\..\Views\Actions\Action.cshtml"
                          , Tuple.Create(Tuple.Create("", 13399), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<ICustomViewModel>).Select(s => s.Serialize()))
            
            #line default
            #line hidden
, 13399), false)
, Tuple.Create(Tuple.Create("", 13493), Tuple.Create("]", 13493), true)
);

WriteLiteral(" />\r\n");

            
            #line 222 "..\..\Views\Actions\Action.cshtml"
                                                }
                                            }
                                            else if (field.Value is IEnumerable<Entity>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 13803), Tuple.Create("\"", 13827)
            
            #line 226 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 13810), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 13810), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 13828), Tuple.Create("\"", 13924)
, Tuple.Create(Tuple.Create("", 13836), Tuple.Create("[", 13836), true)
            
            #line 226 "..\..\Views\Actions\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 13837), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<Entity>).Select(e => e.Id.ToString()))
            
            #line default
            #line hidden
, 13837), false)
, Tuple.Create(Tuple.Create("", 13923), Tuple.Create("]", 13923), true)
);

WriteLiteral(" />\r\n");

            
            #line 227 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is Entity)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 14169), Tuple.Create("\"", 14193)
            
            #line 230 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 14176), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 14176), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 14194), Tuple.Create("\"", 14231)
            
            #line 230 "..\..\Views\Actions\Action.cshtml"
                     , Tuple.Create(Tuple.Create("", 14202), Tuple.Create<System.Object, System.Int32>((field.Value as Entity).Id
            
            #line default
            #line hidden
, 14202), false)
);

WriteLiteral(" />\r\n");

            
            #line 231 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.WidgetFieldAttribute)
                                            {

                                            }
                                            else if (field.Value is bool?[])
                                            {
                                                var values = "";
                                                foreach (var v in (field.Value as IEnumerable<bool?>).ToList())
                                                {
                                                    if (v != null) { values += v + ","; }
                                                    else { values += "null,"; }

                                                }

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 15176), Tuple.Create("\"", 15200)
            
            #line 245 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 15183), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 15183), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 15201), Tuple.Create("\"", 15262)
, Tuple.Create(Tuple.Create("", 15209), Tuple.Create("[", 15209), true)
            
            #line 245 "..\..\Views\Actions\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 15210), Tuple.Create<System.Object, System.Int32>(values.Substring(0, values.Length - 1).ToLower()
            
            #line default
            #line hidden
, 15210), false)
, Tuple.Create(Tuple.Create("", 15261), Tuple.Create("]", 15261), true)
);

WriteLiteral(" />\r\n");

            
            #line 246 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is DateTime)
                                            {
                                                var date = (DateTime)field.Value;

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 15592), Tuple.Create("\"", 15616)
            
            #line 250 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 15599), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 15599), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 15617), Tuple.Create("\"", 15687)
, Tuple.Create(Tuple.Create("", 15625), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 250 "..\..\Views\Actions\Action.cshtml"
                                                                                                      if(date > DateTime.MinValue) { 
            
            #line default
            #line hidden
            
            #line 250 "..\..\Views\Actions\Action.cshtml"
                                                                                              WriteTo(__razor_attribute_value_writer, date.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
            
            #line 250 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                  }
            
            #line default
            #line hidden
}), 15625), false)
);

WriteLiteral(" />\r\n");

            
            #line 251 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is bool)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 15930), Tuple.Create("\"", 15954)
            
            #line 254 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 15937), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 15937), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 15955), Tuple.Create("\"", 15986)
            
            #line 254 "..\..\Views\Actions\Action.cshtml"
                    , Tuple.Create(Tuple.Create("", 15963), Tuple.Create<System.Object, System.Int32>(field.Value.ToString()
            
            #line default
            #line hidden
, 15963), false)
);

WriteLiteral(" />\r\n");

            
            #line 255 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 16204), Tuple.Create("\"", 16228)
            
            #line 258 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 16211), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 16211), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 16229), Tuple.Create("\"", 16249)
            
            #line 258 "..\..\Views\Actions\Action.cshtml"
                    , Tuple.Create(Tuple.Create("", 16237), Tuple.Create<System.Object, System.Int32>(field.Value
            
            #line default
            #line hidden
, 16237), false)
);

WriteLiteral(" />\r\n");

            
            #line 259 "..\..\Views\Actions\Action.cshtml"
                                            }
                                        }


            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"submittedpagenames\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16433), Tuple.Create("\"", 16510)
            
            #line 262 "..\..\Views\Actions\Action.cshtml"
             , Tuple.Create(Tuple.Create("", 16441), Tuple.Create<System.Object, System.Int32>(string.Join(",", Model.SubmittedPages.Select(p => p.GetType().Name))
            
            #line default
            #line hidden
, 16441), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"page\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16588), Tuple.Create("\"", 16622)
            
            #line 263 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 16596), Tuple.Create<System.Object, System.Int32>(Model.Page.GetType().Name
            
            #line default
            #line hidden
, 16596), false)
);

WriteLiteral(" />\r\n");

            
            #line 264 "..\..\Views\Actions\Action.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" style=\"position: absolute; left: -9999px; width: 1px; height: 1px;\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" />\r\n                                </form>\r\n\r\n");

            
            #line 269 "..\..\Views\Actions\Action.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 269 "..\..\Views\Actions\Action.cshtml"
                                 if ((bool)TempData["ShowSubmit"] || Model.SubmittedPages.Count != 0)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"form-group margin-tb-md\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                            <ul");

WriteLiteral(" class=\"pull-right list-inline\"");

WriteLiteral(">\r\n");

            
            #line 274 "..\..\Views\Actions\Action.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 274 "..\..\Views\Actions\Action.cshtml"
                                                 if (Model.SubmittedPages.Count != 0)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-grey uppercase\"");

WriteLiteral(" onclick=\'$(\"#back-form\").submit();\'");

WriteLiteral(">BACK</a></li>\r\n");

            
            #line 277 "..\..\Views\Actions\Action.cshtml"
                                                }
                                                else
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-red uppercase\"");

WriteLiteral(" onclick=\'$(\"#cancel-form\").submit();\'");

WriteLiteral(">CANCEL</a></li>\r\n");

            
            #line 281 "..\..\Views\Actions\Action.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 283 "..\..\Views\Actions\Action.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 283 "..\..\Views\Actions\Action.cshtml"
                                                 if ((bool)TempData["ShowSubmit"])
                                                {
                                                    if (!Model.IsMultiPage)
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-green uppercase\"");

WriteLiteral(" onclick=\'$(\"#main-form\").submit();\'");

WriteLiteral(">");

            
            #line 287 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                 Write(Model.Action.SubmitValue);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 288 "..\..\Views\Actions\Action.cshtml"
                                                    }
                                                    else
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-grey uppercase\"");

WriteLiteral(" onclick=\'$(\"#main-form\").submit();\'");

WriteLiteral(">");

            
            #line 291 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                Write(Model.Action.SubmitValue);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 292 "..\..\Views\Actions\Action.cshtml"
                                                    }
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </ul>\r\n                              " +
"          </div>\r\n                                    </div>\r\n");

            
            #line 297 "..\..\Views\Actions\Action.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n                        </div>\r\n\r\n");

            
            #line 301 "..\..\Views\Actions\Action.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 301 "..\..\Views\Actions\Action.cshtml"
                         if (Model.IsMultiPage)
                        {
                            if (Model.SubmittedPages.Count != 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" id=\"back-form\"");

WriteLiteral(">\r\n");

            
            #line 306 "..\..\Views\Actions\Action.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 306 "..\..\Views\Actions\Action.cshtml"
                                     if (hidden != null)
                                    {
                                        foreach (var field in hidden)
                                        {
                                            if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.BulkFileUploadFieldAttribute && field.Value is IEnumerable<Attachment>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 19933), Tuple.Create("\"", 19957)
            
            #line 312 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 19940), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 19940), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 19958), Tuple.Create("\"", 20044)
, Tuple.Create(Tuple.Create("", 19966), Tuple.Create("[", 19966), true)
, Tuple.Create(Tuple.Create("", 19967), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 312 "..\..\Views\Actions\Action.cshtml"
                                                                                                       foreach (var a in field.Value as IEnumerable<Attachment>) { 
            
            #line default
            #line hidden
            
            #line 312 "..\..\Views\Actions\Action.cshtml"
                                                                                                                             WriteTo(__razor_attribute_value_writer, a.Id + ",");

            
            #line default
            #line hidden
            
            #line 312 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                 }
            
            #line default
            #line hidden
}), 19967), false)
, Tuple.Create(Tuple.Create("", 20043), Tuple.Create("]", 20043), true)
);

WriteLiteral(" />\r\n");

            
            #line 313 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<Attachment>)
                                            {
                                                foreach (var file in (IEnumerable<Attachment>)field.Value)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 20469), Tuple.Create("\"", 20493)
            
            #line 318 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 20476), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 20476), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 20494), Tuple.Create("\"", 20512)
            
            #line 318 "..\..\Views\Actions\Action.cshtml"
                         , Tuple.Create(Tuple.Create("", 20502), Tuple.Create<System.Object, System.Int32>(file.Id
            
            #line default
            #line hidden
, 20502), false)
);

WriteLiteral(" />");

            
            #line 318 "..\..\Views\Actions\Action.cshtml"
                                                                                                                       }
                                            }
                                            else if (field.Value is ICustomViewModel)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 20768), Tuple.Create("\"", 20792)
            
            #line 322 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 20775), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 20775), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 20793), Tuple.Create("\"", 20849)
            
            #line 322 "..\..\Views\Actions\Action.cshtml"
                     , Tuple.Create(Tuple.Create("", 20801), Tuple.Create<System.Object, System.Int32>((field.Value as ICustomViewModel).Serialize()
            
            #line default
            #line hidden
, 20801), false)
);

WriteLiteral(" />\r\n");

            
            #line 323 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<ICustomViewModel>)
                                            {
                                                if ((field.Value as IEnumerable<ICustomViewModel>).Count() > 0)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 21285), Tuple.Create("\"", 21309)
            
            #line 328 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 21292), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 21292), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 21310), Tuple.Create("\"", 21414)
, Tuple.Create(Tuple.Create("", 21318), Tuple.Create("[", 21318), true)
            
            #line 328 "..\..\Views\Actions\Action.cshtml"
                          , Tuple.Create(Tuple.Create("", 21319), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<ICustomViewModel>).Select(s => s.Serialize()))
            
            #line default
            #line hidden
, 21319), false)
, Tuple.Create(Tuple.Create("", 21413), Tuple.Create("]", 21413), true)
);

WriteLiteral(" />");

            
            #line 328 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                                             }
                                            }
                                            else if (field.Value is Entity)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 21660), Tuple.Create("\"", 21684)
            
            #line 332 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 21667), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 21667), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 21685), Tuple.Create("\"", 21722)
            
            #line 332 "..\..\Views\Actions\Action.cshtml"
                     , Tuple.Create(Tuple.Create("", 21693), Tuple.Create<System.Object, System.Int32>((field.Value as Entity).Id
            
            #line default
            #line hidden
, 21693), false)
);

WriteLiteral(" />\r\n");

            
            #line 333 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<Entity>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 21980), Tuple.Create("\"", 22004)
            
            #line 336 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 21987), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 21987), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 22005), Tuple.Create("\"", 22101)
, Tuple.Create(Tuple.Create("", 22013), Tuple.Create("[", 22013), true)
            
            #line 336 "..\..\Views\Actions\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 22014), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<Entity>).Select(e => e.Id.ToString()))
            
            #line default
            #line hidden
, 22014), false)
, Tuple.Create(Tuple.Create("", 22100), Tuple.Create("]", 22100), true)
);

WriteLiteral(" />\r\n");

            
            #line 337 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.WidgetFieldAttribute)
                                            {

                                            }
                                            else if (field.Value is bool?[])
                                            {
                                                var values = "";
                                                foreach (var v in (field.Value as IEnumerable<bool?>).ToList())
                                                {
                                                    if (v != null) { values += v + ","; }
                                                    else { values += "null,"; }

                                                }

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 23046), Tuple.Create("\"", 23070)
            
            #line 351 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 23053), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 23053), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 23071), Tuple.Create("\"", 23132)
, Tuple.Create(Tuple.Create("", 23079), Tuple.Create("[", 23079), true)
            
            #line 351 "..\..\Views\Actions\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 23080), Tuple.Create<System.Object, System.Int32>(values.Substring(0, values.Length - 1).ToLower()
            
            #line default
            #line hidden
, 23080), false)
, Tuple.Create(Tuple.Create("", 23131), Tuple.Create("]", 23131), true)
);

WriteLiteral(" />\r\n");

            
            #line 352 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is DateTime)
                                            {
                                                var date = (DateTime)field.Value;

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 23462), Tuple.Create("\"", 23486)
            
            #line 356 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 23469), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 23469), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 23487), Tuple.Create("\"", 23557)
, Tuple.Create(Tuple.Create("", 23495), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 356 "..\..\Views\Actions\Action.cshtml"
                                                                                                      if(date > DateTime.MinValue) { 
            
            #line default
            #line hidden
            
            #line 356 "..\..\Views\Actions\Action.cshtml"
                                                                                              WriteTo(__razor_attribute_value_writer, date.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
            
            #line 356 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                  }
            
            #line default
            #line hidden
}), 23495), false)
);

WriteLiteral(" />\r\n");

            
            #line 357 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is bool)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 23800), Tuple.Create("\"", 23824)
            
            #line 360 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 23807), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 23807), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 23825), Tuple.Create("\"", 23856)
            
            #line 360 "..\..\Views\Actions\Action.cshtml"
                    , Tuple.Create(Tuple.Create("", 23833), Tuple.Create<System.Object, System.Int32>(field.Value.ToString()
            
            #line default
            #line hidden
, 23833), false)
);

WriteLiteral(" />\r\n");

            
            #line 361 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 24074), Tuple.Create("\"", 24098)
            
            #line 364 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 24081), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 24081), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 24099), Tuple.Create("\"", 24119)
            
            #line 364 "..\..\Views\Actions\Action.cshtml"
                    , Tuple.Create(Tuple.Create("", 24107), Tuple.Create<System.Object, System.Int32>(field.Value
            
            #line default
            #line hidden
, 24107), false)
);

WriteLiteral(" />\r\n");

            
            #line 365 "..\..\Views\Actions\Action.cshtml"
                                            }
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"submittedpagenames\"");

WriteAttribute("value", Tuple.Create(" value=\"", 24301), Tuple.Create("\"", 24378)
            
            #line 367 "..\..\Views\Actions\Action.cshtml"
             , Tuple.Create(Tuple.Create("", 24309), Tuple.Create<System.Object, System.Int32>(string.Join(",", Model.SubmittedPages.Select(p => p.GetType().Name))
            
            #line default
            #line hidden
, 24309), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"page\"");

WriteAttribute("value", Tuple.Create(" value=\"", 24456), Tuple.Create("\"", 24490)
            
            #line 368 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 24464), Tuple.Create<System.Object, System.Int32>(Model.Page.GetType().Name
            
            #line default
            #line hidden
, 24464), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"back\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n");

            
            #line 370 "..\..\Views\Actions\Action.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </form>\r\n");

            
            #line 372 "..\..\Views\Actions\Action.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" id=\"cancel-form\"");

WriteAttribute("action", Tuple.Create(" action=\"", 24784), Tuple.Create("\"", 24811)
            
            #line 374 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 24793), Tuple.Create<System.Object, System.Int32>(cancelActionUrl
            
            #line default
            #line hidden
, 24793), false)
);

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"cancel\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n                        </form>\r\n                    </div>\r\n\r\n             " +
"   </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <script>\r\n            $(document).ready(function () {\r\n                $(" +
"\"#loader-wrapper\").removeClass(\'hide-bg\');\r\n                setTimeout(function " +
"() { $(\"#loader-wrapper\").css(\'display\', \'none\'); }, 500);\r\n            });\r\n   " +
"         $(\'#main-form-submit\').click(function (e) {\r\n                e.preventD" +
"efault()\r\n                var bValid = true;\r\n                $(document).find(\'" +
"input.required:visible\').each(function () {\r\n                    var formgroup =" +
" $(this).closest(\'.form-group\');\r\n                    if ($(this).val() === \'\') " +
"{\r\n                        formgroup.addClass(\'has-error\');\r\n                   " +
"     var label = formgroup.find(\'label.control-label\').text();\r\n\r\n              " +
"          console.log(formgroup.find(\'div\').index(0));\r\n                        " +
"if ($(this).closest(\'.col-md-9\').find(\'span.help-block\').length == 0)\r\n         " +
"                   $(this).closest(\'.col-md-9\').append(\'<span class=\"help-block\"" +
">The \' + label + \' field is required.</span>\');\r\n\r\n                        bVali" +
"d = false;\r\n                    } else {\r\n                        formgroup.remo" +
"veClass(\'has-error\');\r\n                        formgroup.find(\'span.help-block\')" +
".remove();\r\n                    }\r\n                });\r\n\r\n                if (bV" +
"alid) {\r\n                    setTimeout(function () { $(\"#loader-wrapper\").css(\'" +
"display\', \'block\'); }, 500);\r\n                    $(\"#loader-wrapper\").addClass(" +
"\'hide-bg\');\r\n                    $(\'#main-form\').submit.disabled = true;\r\n      " +
"              $(\'#main-form\').submit();\r\n                }\r\n            });\r\n   " +
"     </script>\r\n");

            
            #line 415 "..\..\Views\Actions\Action.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 419 "..\..\Views\Actions\Action.cshtml"
Write(Html.RenderDelayed());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
