#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    
    #line 9 "..\..\Views\Actions\Action.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    
    #line 8 "..\..\Views\Actions\Action.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Actions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Entities;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Interfaces;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Web.Utilities;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Enquiries.Entities;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Enquiries.Interfaces;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Actions/Action.cshtml")]
    public partial class _Views_Actions_Action_cshtml : System.Web.Mvc.WebViewPage<Realtair.Framework.Core.Web.Controllers.ActionsController.ActionViewModel>
    {
        public _Views_Actions_Action_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Actions\Action.cshtml"
  
    var detailsTemplate = "-";
    var cancelActionUrl = "";

    if (Request.QueryString["ReturnUrl"] != null)
    {
        cancelActionUrl = Request.QueryString["ReturnUrl"].ToString();
    }

    if (Model.Action.This != null)
    {
        detailsTemplate = $"{Model.Action.This.ActualType().Name}/{Model.Action.GetType().Name}";
    }

    if (Html.ViewExists(detailsTemplate))
    {
        Layout = null;
        Html.RenderPartial(detailsTemplate, Model.Action);
    }
    else
    {
        IEnumerable<Field> shown;
        IEnumerable<Field> shownWithFieldSets;
        IEnumerable<Field> hidden;

        TempData["ShowSubmit"] = true;

        if (Model.IsMultiPage)
        {
            shown = Model.FieldsForPage;
            shownWithFieldSets = Model.FieldsForPage.Where(f => f.FieldSetAttribute != null).ToList();
            hidden = Model.HiddenFieldsForPage;
        }
        else
        {
            shown = Model.Fields;
            shownWithFieldSets = Model.Fields.Where(f => f.FieldSetAttribute != null).ToList();
            hidden = null;
        }


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"content bg-grey-lt\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"loader-wrapper\"");

WriteLiteral(" class=\"hide-bg\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"loader\"");

WriteLiteral("></div>\r\n            </div>\r\n\r\n");

WriteLiteral("            ");

            
            #line 56 "..\..\Views\Actions\Action.cshtml"
       Write(Html.Partial("FlowerHorn/MobileNavigation"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" id=\"page-wrapper\"");

WriteLiteral(" class=\"padding-sides-sm pad-form-mob\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-sm-10 col-sm-offset-1\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                        <h2");

WriteLiteral(" class=\"hidden-xs\"");

WriteLiteral(">\r\n");

            
            #line 63 "..\..\Views\Actions\Action.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Actions\Action.cshtml"
                             if (Model.IsMultiPage)
                            {
                                
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Actions\Action.cshtml"
                           Write(Model.Page.Name.ToUpper());

            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Actions\Action.cshtml"
                                                          
                            }
                            else
                            {
                                
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Actions\Action.cshtml"
                           Write(Model.Action.Description(Html.LoggedInUser()).ToUpper());

            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\Actions\Action.cshtml"
                                                                                        
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </h2>\r\n\r\n");

            
            #line 73 "..\..\Views\Actions\Action.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 73 "..\..\Views\Actions\Action.cshtml"
                          
                            var parentEnquiry = (Model.Action.This as IHasParentEnquiry)?.ParentEnquiry;
                            if (parentEnquiry != null)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <h3");

WriteLiteral(" class=\"action-sub-margin\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-home\"");

WriteLiteral("></i> ");

            
            #line 78 "..\..\Views\Actions\Action.cshtml"
                                                           Write(parentEnquiry.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </h3>\r\n");

WriteLiteral("                                <br />\r\n");

            
            #line 81 "..\..\Views\Actions\Action.cshtml"
                            }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        ");

WriteLiteral("\r\n");

            
            #line 85 "..\..\Views\Actions\Action.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 85 "..\..\Views\Actions\Action.cshtml"
                         if (Model.Action.HasValidated && !Model.Action.IsValid)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" style=\"padding: 0;\"");

WriteLiteral(">\r\n");

            
            #line 88 "..\..\Views\Actions\Action.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Actions\Action.cshtml"
                                 foreach (var error in Model.Action.Errors.Where(e => e.MemberNames.Count() == 0))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">");

            
            #line 90 "..\..\Views\Actions\Action.cshtml"
                                                               Write(error.ErrorMessage);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 91 "..\..\Views\Actions\Action.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n");

            
            #line 93 "..\..\Views\Actions\Action.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <form");

WriteLiteral(" class=\"form-horizontal panel panel-body form-padding\"");

WriteLiteral(" id=\"main-form\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

            
            #line 133 "..\..\Views\Actions\Action.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 133 "..\..\Views\Actions\Action.cshtml"
                                     foreach (var field in shown)
                                    {
                                        if (field.FieldSetAttribute != null)
                                        {
                                            var fieldSetItems = shownWithFieldSets.Where(s => s.FieldSetAttribute.Legend == field.FieldSetAttribute.Legend).ToList();
                                            if (fieldSetItems.Any())
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <fieldset");

WriteAttribute("class", Tuple.Create(" class=\"", 6911), Tuple.Create("\"", 7065)
            
            #line 140 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 6919), Tuple.Create<System.Object, System.Int32>(shownWithFieldSets.First().UniqueName == shown.First().UniqueName && fieldSetItems.First().UniqueName == field.UniqueName ? "" : "margin-t-md2"
            
            #line default
            #line hidden
, 6919), false)
);

WriteLiteral(">\r\n                                                    <legend>");

            
            #line 141 "..\..\Views\Actions\Action.cshtml"
                                                       Write(field.FieldSetAttribute.Legend);

            
            #line default
            #line hidden
WriteLiteral("</legend>\r\n                                                    <div");

WriteLiteral(" class=\"p-l-30\"");

WriteLiteral(">\r\n");

            
            #line 143 "..\..\Views\Actions\Action.cshtml"
                                                        
            
            #line default
            #line hidden
            
            #line 143 "..\..\Views\Actions\Action.cshtml"
                                                         foreach (var item in fieldSetItems)
                                                        {
                                                            var fieldWithReturnType = $"Fields/_{item.PropertyType.Name}_{item.FieldAttribute.GetType().Name.Substring(0, item.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                                            var fieldWithoutReturnType = $"Fields/_{item.FieldAttribute.GetType().Name.Substring(0, item.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                                            var fieldThatWorksForBoth = $"Fields/_{item.PropertyType.Name}_Field";

                                                            if (Html.ViewExists(fieldWithReturnType))
                                                            {
                                                                Html.RenderPartial(fieldWithReturnType, item);
                                                            }
                                                            else if (Html.ViewExists(fieldWithoutReturnType))
                                                            {
                                                                Html.RenderPartial(fieldWithoutReturnType, item);
                                                            }
                                                            else if (Html.ViewExists(fieldThatWorksForBoth))
                                                            {
                                                                Html.RenderPartial(fieldThatWorksForBoth, item);
                                                            }
                                                            else
                                                            {


            
            #line default
            #line hidden
WriteLiteral("                                                                <p> Cannot render" +
" field view, looked for both ");

            
            #line 164 "..\..\Views\Actions\Action.cshtml"
                                                                                                         Write(fieldWithReturnType);

            
            #line default
            #line hidden
WriteLiteral(" and ");

            
            #line 164 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                  Write(fieldWithoutReturnType);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n");

            
            #line 165 "..\..\Views\Actions\Action.cshtml"

                                                            }
                                                        }

            
            #line default
            #line hidden
WriteLiteral("                                                    </div>\r\n                     " +
"                           </fieldset>");

            
            #line 169 "..\..\Views\Actions\Action.cshtml"
                                                           shownWithFieldSets = shownWithFieldSets.Except(fieldSetItems).ToList();
                                            }
                                        }
                                        else
                                        {
                                            var fieldWithReturnType = $"Fields/_{field.PropertyType.Name}_{field.FieldAttribute.GetType().Name.Substring(0, field.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                            var fieldWithoutReturnType = $"Fields/_{field.FieldAttribute.GetType().Name.Substring(0, field.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                            var fieldThatWorksForBoth = $"Fields/_{field.PropertyType.Name}_Field";

                                            if (Html.ViewExists(fieldWithReturnType))
                                            {
                                                Html.RenderPartial(fieldWithReturnType, field);
                                            }
                                            else if (Html.ViewExists(fieldWithoutReturnType))
                                            {
                                                Html.RenderPartial(fieldWithoutReturnType, field);
                                            }
                                            else if (Html.ViewExists(fieldThatWorksForBoth))
                                            {
                                                Html.RenderPartial(fieldThatWorksForBoth, field);
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <p>Cannot render field view, look" +
"ed for both ");

            
            #line 192 "..\..\Views\Actions\Action.cshtml"
                                                                                        Write(fieldWithReturnType);

            
            #line default
            #line hidden
WriteLiteral(" and ");

            
            #line 192 "..\..\Views\Actions\Action.cshtml"
                                                                                                                 Write(fieldWithoutReturnType);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 193 "..\..\Views\Actions\Action.cshtml"
                                            }
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 197 "..\..\Views\Actions\Action.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 197 "..\..\Views\Actions\Action.cshtml"
                                     if (hidden != null)
                                    {
                                        foreach (var field in hidden)
                                        {
                                            if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.BulkFileUploadFieldAttribute && field.Value is IEnumerable<Attachment>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 12124), Tuple.Create("\"", 12148)
            
            #line 203 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 12131), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 12131), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 12149), Tuple.Create("\"", 12235)
, Tuple.Create(Tuple.Create("", 12157), Tuple.Create("[", 12157), true)
, Tuple.Create(Tuple.Create("", 12158), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 203 "..\..\Views\Actions\Action.cshtml"
                                                                                                                 foreach (var a in field.Value as IEnumerable<Attachment>) { 
            
            #line default
            #line hidden
            
            #line 203 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                       WriteTo(__razor_attribute_value_writer, a.Id + ",");

            
            #line default
            #line hidden
            
            #line 203 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                           }
            
            #line default
            #line hidden
}), 12158), false)
, Tuple.Create(Tuple.Create("", 12234), Tuple.Create("]", 12234), true)
);

WriteLiteral(" />\r\n");

            
            #line 204 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IList<Attachment>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 12501), Tuple.Create("\"", 12525)
            
            #line 207 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 12508), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 12508), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 12526), Tuple.Create("\"", 12617)
, Tuple.Create(Tuple.Create("", 12534), Tuple.Create("[", 12534), true)
            
            #line 207 "..\..\Views\Actions\Action.cshtml"
                                , Tuple.Create(Tuple.Create("", 12535), Tuple.Create<System.Object, System.Int32>(string.Join(",",((IList<Attachment>)field.Value).Select(f => f.Id.ToString()))
            
            #line default
            #line hidden
, 12535), false)
, Tuple.Create(Tuple.Create("", 12616), Tuple.Create("]", 12616), true)
);

WriteLiteral(" />\r\n");

            
            #line 208 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is ICustomViewModel)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 12882), Tuple.Create("\"", 12906)
            
            #line 211 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 12889), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 12889), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 12907), Tuple.Create("\"", 12963)
            
            #line 211 "..\..\Views\Actions\Action.cshtml"
                               , Tuple.Create(Tuple.Create("", 12915), Tuple.Create<System.Object, System.Int32>((field.Value as ICustomViewModel).Serialize()
            
            #line default
            #line hidden
, 12915), false)
);

WriteLiteral(" />\r\n");

            
            #line 212 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<ICustomViewModel>)
                                            {
                                                if ((field.Value as IEnumerable<ICustomViewModel>).Count() > 0)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 13409), Tuple.Create("\"", 13433)
            
            #line 217 "..\..\Views\Actions\Action.cshtml"
        , Tuple.Create(Tuple.Create("", 13416), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 13416), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 13434), Tuple.Create("\"", 13538)
, Tuple.Create(Tuple.Create("", 13442), Tuple.Create("[", 13442), true)
            
            #line 217 "..\..\Views\Actions\Action.cshtml"
                                    , Tuple.Create(Tuple.Create("", 13443), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<ICustomViewModel>).Select(s => s.Serialize()))
            
            #line default
            #line hidden
, 13443), false)
, Tuple.Create(Tuple.Create("", 13537), Tuple.Create("]", 13537), true)
);

WriteLiteral(" />\r\n");

            
            #line 218 "..\..\Views\Actions\Action.cshtml"
                                                }
                                            }
                                            else if (field.Value is IEnumerable<Entity>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 13857), Tuple.Create("\"", 13881)
            
            #line 222 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 13864), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 13864), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 13882), Tuple.Create("\"", 13978)
, Tuple.Create(Tuple.Create("", 13890), Tuple.Create("[", 13890), true)
            
            #line 222 "..\..\Views\Actions\Action.cshtml"
                                , Tuple.Create(Tuple.Create("", 13891), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<Entity>).Select(e => e.Id.ToString()))
            
            #line default
            #line hidden
, 13891), false)
, Tuple.Create(Tuple.Create("", 13977), Tuple.Create("]", 13977), true)
);

WriteLiteral(" />\r\n");

            
            #line 223 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is Entity)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 14233), Tuple.Create("\"", 14257)
            
            #line 226 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 14240), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 14240), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 14258), Tuple.Create("\"", 14295)
            
            #line 226 "..\..\Views\Actions\Action.cshtml"
                               , Tuple.Create(Tuple.Create("", 14266), Tuple.Create<System.Object, System.Int32>((field.Value as Entity).Id
            
            #line default
            #line hidden
, 14266), false)
);

WriteLiteral(" />\r\n");

            
            #line 227 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.WidgetFieldAttribute)
                                            {

                                            }
                                            else if (field.Value is bool?[])
                                            {
                                                var values = "";
                                                foreach (var v in (field.Value as IEnumerable<bool?>).ToList())
                                                {
                                                    if (v != null) { values += v + ","; }
                                                    else { values += "null,"; }

                                                }

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 15250), Tuple.Create("\"", 15274)
            
            #line 241 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 15257), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 15257), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 15275), Tuple.Create("\"", 15336)
, Tuple.Create(Tuple.Create("", 15283), Tuple.Create("[", 15283), true)
            
            #line 241 "..\..\Views\Actions\Action.cshtml"
                                , Tuple.Create(Tuple.Create("", 15284), Tuple.Create<System.Object, System.Int32>(values.Substring(0, values.Length - 1).ToLower()
            
            #line default
            #line hidden
, 15284), false)
, Tuple.Create(Tuple.Create("", 15335), Tuple.Create("]", 15335), true)
);

WriteLiteral(" />\r\n");

            
            #line 242 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is DateTime)
                                            {
                                                var date = (DateTime)field.Value;

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 15676), Tuple.Create("\"", 15700)
            
            #line 246 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 15683), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 15683), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 15701), Tuple.Create("\"", 15771)
, Tuple.Create(Tuple.Create("", 15709), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 246 "..\..\Views\Actions\Action.cshtml"
                                                                                                                if(date > DateTime.MinValue) { 
            
            #line default
            #line hidden
            
            #line 246 "..\..\Views\Actions\Action.cshtml"
                                                                                                        WriteTo(__razor_attribute_value_writer, date.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
            
            #line 246 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                            }
            
            #line default
            #line hidden
}), 15709), false)
);

WriteLiteral(" />\r\n");

            
            #line 247 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is bool)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 16024), Tuple.Create("\"", 16048)
            
            #line 250 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 16031), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 16031), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 16049), Tuple.Create("\"", 16080)
            
            #line 250 "..\..\Views\Actions\Action.cshtml"
                              , Tuple.Create(Tuple.Create("", 16057), Tuple.Create<System.Object, System.Int32>(field.Value.ToString()
            
            #line default
            #line hidden
, 16057), false)
);

WriteLiteral(" />\r\n");

            
            #line 251 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 16308), Tuple.Create("\"", 16332)
            
            #line 254 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 16315), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 16315), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 16333), Tuple.Create("\"", 16353)
            
            #line 254 "..\..\Views\Actions\Action.cshtml"
                              , Tuple.Create(Tuple.Create("", 16341), Tuple.Create<System.Object, System.Int32>(field.Value
            
            #line default
            #line hidden
, 16341), false)
);

WriteLiteral(" />\r\n");

            
            #line 255 "..\..\Views\Actions\Action.cshtml"
                                            }
                                        }


            
            #line default
            #line hidden
WriteLiteral("                                        <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"submittedpagenames\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16547), Tuple.Create("\"", 16624)
            
            #line 258 "..\..\Views\Actions\Action.cshtml"
                       , Tuple.Create(Tuple.Create("", 16555), Tuple.Create<System.Object, System.Int32>(string.Join(",", Model.SubmittedPages.Select(p => p.GetType().Name))
            
            #line default
            #line hidden
, 16555), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                        <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"page\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16712), Tuple.Create("\"", 16746)
            
            #line 259 "..\..\Views\Actions\Action.cshtml"
         , Tuple.Create(Tuple.Create("", 16720), Tuple.Create<System.Object, System.Int32>(Model.Page.GetType().Name
            
            #line default
            #line hidden
, 16720), false)
);

WriteLiteral(" />\r\n");

            
            #line 260 "..\..\Views\Actions\Action.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <input autofocus");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" style=\"position: absolute; left: -9999px; width: 1px; height: 1px;\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" />\r\n                                </form>\r\n\r\n");

            
            #line 265 "..\..\Views\Actions\Action.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 265 "..\..\Views\Actions\Action.cshtml"
                                 if ((bool)TempData["ShowSubmit"] || Model.SubmittedPages.Count != 0)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"form-group margin-tb-md\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                            <ul");

WriteLiteral(" class=\"pull-right list-inline\"");

WriteLiteral(">\r\n");

            
            #line 270 "..\..\Views\Actions\Action.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 270 "..\..\Views\Actions\Action.cshtml"
                                                 if (Model.SubmittedPages.Count != 0)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-grey uppercase\"");

WriteLiteral(" onclick=\'$(\"#back-form\").submit();\'");

WriteLiteral(">BACK</a></li>\r\n");

            
            #line 273 "..\..\Views\Actions\Action.cshtml"
                                                }
                                                else
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-grey uppercase\"");

WriteLiteral(" onclick=\'$(\"#cancel-form\").submit();\'");

WriteLiteral(">CANCEL</a></li>\r\n");

            
            #line 277 "..\..\Views\Actions\Action.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 279 "..\..\Views\Actions\Action.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 279 "..\..\Views\Actions\Action.cshtml"
                                                 if ((bool)TempData["ShowSubmit"])
                                                {
                                                    if (!Model.IsMultiPage)
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-green uppercase\"");

WriteLiteral(" id=\"main-form-submit\"");

WriteLiteral(">");

            
            #line 283 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                   Write(Model.Action.SubmitValue);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 284 "..\..\Views\Actions\Action.cshtml"
                                                    }
                                                    else
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-green uppercase\"");

WriteLiteral(" id=\"main-form-submit\"");

WriteLiteral(">");

            
            #line 287 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                   Write(Model.Action.SubmitValue);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 288 "..\..\Views\Actions\Action.cshtml"
                                                    }
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </ul>\r\n                              " +
"          </div>\r\n                                    </div>\r\n");

            
            #line 293 "..\..\Views\Actions\Action.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n                        </div>\r\n\r\n");

            
            #line 297 "..\..\Views\Actions\Action.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 297 "..\..\Views\Actions\Action.cshtml"
                         if (Model.IsMultiPage)
                        {
                            if (Model.SubmittedPages.Count != 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" id=\"back-form\"");

WriteLiteral(">\r\n");

            
            #line 302 "..\..\Views\Actions\Action.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 302 "..\..\Views\Actions\Action.cshtml"
                                     if (hidden != null)
                                    {
                                        foreach (var field in hidden)
                                        {
                                            if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.BulkFileUploadFieldAttribute && field.Value is IEnumerable<Attachment>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 20051), Tuple.Create("\"", 20075)
            
            #line 308 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 20058), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 20058), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 20076), Tuple.Create("\"", 20162)
, Tuple.Create(Tuple.Create("", 20084), Tuple.Create("[", 20084), true)
, Tuple.Create(Tuple.Create("", 20085), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 308 "..\..\Views\Actions\Action.cshtml"
                                                                                                                 foreach (var a in field.Value as IEnumerable<Attachment>) { 
            
            #line default
            #line hidden
            
            #line 308 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                       WriteTo(__razor_attribute_value_writer, a.Id + ",");

            
            #line default
            #line hidden
            
            #line 308 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                           }
            
            #line default
            #line hidden
}), 20085), false)
, Tuple.Create(Tuple.Create("", 20161), Tuple.Create("]", 20161), true)
);

WriteLiteral(" />\r\n");

            
            #line 309 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<Attachment>)
                                            {
                                                foreach (var file in (IEnumerable<Attachment>)field.Value)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 20597), Tuple.Create("\"", 20621)
            
            #line 314 "..\..\Views\Actions\Action.cshtml"
        , Tuple.Create(Tuple.Create("", 20604), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 20604), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 20622), Tuple.Create("\"", 20640)
            
            #line 314 "..\..\Views\Actions\Action.cshtml"
                                   , Tuple.Create(Tuple.Create("", 20630), Tuple.Create<System.Object, System.Int32>(file.Id
            
            #line default
            #line hidden
, 20630), false)
);

WriteLiteral(" />");

            
            #line 314 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                 }
                                            }
                                            else if (field.Value is ICustomViewModel)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 20906), Tuple.Create("\"", 20930)
            
            #line 318 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 20913), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 20913), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 20931), Tuple.Create("\"", 20987)
            
            #line 318 "..\..\Views\Actions\Action.cshtml"
                               , Tuple.Create(Tuple.Create("", 20939), Tuple.Create<System.Object, System.Int32>((field.Value as ICustomViewModel).Serialize()
            
            #line default
            #line hidden
, 20939), false)
);

WriteLiteral(" />\r\n");

            
            #line 319 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<ICustomViewModel>)
                                            {
                                                if ((field.Value as IEnumerable<ICustomViewModel>).Count() > 0)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 21433), Tuple.Create("\"", 21457)
            
            #line 324 "..\..\Views\Actions\Action.cshtml"
        , Tuple.Create(Tuple.Create("", 21440), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 21440), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 21458), Tuple.Create("\"", 21562)
, Tuple.Create(Tuple.Create("", 21466), Tuple.Create("[", 21466), true)
            
            #line 324 "..\..\Views\Actions\Action.cshtml"
                                    , Tuple.Create(Tuple.Create("", 21467), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<ICustomViewModel>).Select(s => s.Serialize()))
            
            #line default
            #line hidden
, 21467), false)
, Tuple.Create(Tuple.Create("", 21561), Tuple.Create("]", 21561), true)
);

WriteLiteral(" />");

            
            #line 324 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                                                       }
                                            }
                                            else if (field.Value is Entity)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 21818), Tuple.Create("\"", 21842)
            
            #line 328 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 21825), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 21825), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 21843), Tuple.Create("\"", 21880)
            
            #line 328 "..\..\Views\Actions\Action.cshtml"
                               , Tuple.Create(Tuple.Create("", 21851), Tuple.Create<System.Object, System.Int32>((field.Value as Entity).Id
            
            #line default
            #line hidden
, 21851), false)
);

WriteLiteral(" />\r\n");

            
            #line 329 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<Entity>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 22148), Tuple.Create("\"", 22172)
            
            #line 332 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 22155), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 22155), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 22173), Tuple.Create("\"", 22269)
, Tuple.Create(Tuple.Create("", 22181), Tuple.Create("[", 22181), true)
            
            #line 332 "..\..\Views\Actions\Action.cshtml"
                                , Tuple.Create(Tuple.Create("", 22182), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<Entity>).Select(e => e.Id.ToString()))
            
            #line default
            #line hidden
, 22182), false)
, Tuple.Create(Tuple.Create("", 22268), Tuple.Create("]", 22268), true)
);

WriteLiteral(" />\r\n");

            
            #line 333 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.WidgetFieldAttribute)
                                            {

                                            }
                                            else if (field.Value is bool?[])
                                            {
                                                var values = "";
                                                foreach (var v in (field.Value as IEnumerable<bool?>).ToList())
                                                {
                                                    if (v != null) { values += v + ","; }
                                                    else { values += "null,"; }

                                                }

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 23224), Tuple.Create("\"", 23248)
            
            #line 347 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 23231), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 23231), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 23249), Tuple.Create("\"", 23310)
, Tuple.Create(Tuple.Create("", 23257), Tuple.Create("[", 23257), true)
            
            #line 347 "..\..\Views\Actions\Action.cshtml"
                                , Tuple.Create(Tuple.Create("", 23258), Tuple.Create<System.Object, System.Int32>(values.Substring(0, values.Length - 1).ToLower()
            
            #line default
            #line hidden
, 23258), false)
, Tuple.Create(Tuple.Create("", 23309), Tuple.Create("]", 23309), true)
);

WriteLiteral(" />\r\n");

            
            #line 348 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is DateTime)
                                            {
                                                var date = (DateTime)field.Value;

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 23650), Tuple.Create("\"", 23674)
            
            #line 352 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 23657), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 23657), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 23675), Tuple.Create("\"", 23745)
, Tuple.Create(Tuple.Create("", 23683), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 352 "..\..\Views\Actions\Action.cshtml"
                                                                                                                if(date > DateTime.MinValue) { 
            
            #line default
            #line hidden
            
            #line 352 "..\..\Views\Actions\Action.cshtml"
                                                                                                        WriteTo(__razor_attribute_value_writer, date.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
            
            #line 352 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                            }
            
            #line default
            #line hidden
}), 23683), false)
);

WriteLiteral(" />\r\n");

            
            #line 353 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is bool)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 23998), Tuple.Create("\"", 24022)
            
            #line 356 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 24005), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 24005), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 24023), Tuple.Create("\"", 24054)
            
            #line 356 "..\..\Views\Actions\Action.cshtml"
                              , Tuple.Create(Tuple.Create("", 24031), Tuple.Create<System.Object, System.Int32>(field.Value.ToString()
            
            #line default
            #line hidden
, 24031), false)
);

WriteLiteral(" />\r\n");

            
            #line 357 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 24282), Tuple.Create("\"", 24306)
            
            #line 360 "..\..\Views\Actions\Action.cshtml"
    , Tuple.Create(Tuple.Create("", 24289), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 24289), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 24307), Tuple.Create("\"", 24327)
            
            #line 360 "..\..\Views\Actions\Action.cshtml"
                              , Tuple.Create(Tuple.Create("", 24315), Tuple.Create<System.Object, System.Int32>(field.Value
            
            #line default
            #line hidden
, 24315), false)
);

WriteLiteral(" />\r\n");

            
            #line 361 "..\..\Views\Actions\Action.cshtml"
                                            }
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                        <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"submittedpagenames\"");

WriteAttribute("value", Tuple.Create(" value=\"", 24519), Tuple.Create("\"", 24596)
            
            #line 363 "..\..\Views\Actions\Action.cshtml"
                       , Tuple.Create(Tuple.Create("", 24527), Tuple.Create<System.Object, System.Int32>(string.Join(",", Model.SubmittedPages.Select(p => p.GetType().Name))
            
            #line default
            #line hidden
, 24527), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                        <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"page\"");

WriteAttribute("value", Tuple.Create(" value=\"", 24684), Tuple.Create("\"", 24718)
            
            #line 364 "..\..\Views\Actions\Action.cshtml"
         , Tuple.Create(Tuple.Create("", 24692), Tuple.Create<System.Object, System.Int32>(Model.Page.GetType().Name
            
            #line default
            #line hidden
, 24692), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                        <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"back\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n");

            
            #line 366 "..\..\Views\Actions\Action.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </form>\r\n");

            
            #line 368 "..\..\Views\Actions\Action.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" id=\"cancel-form\"");

WriteAttribute("action", Tuple.Create(" action=\"", 25022), Tuple.Create("\"", 25049)
            
            #line 370 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 25031), Tuple.Create<System.Object, System.Int32>(cancelActionUrl
            
            #line default
            #line hidden
, 25031), false)
);

WriteLiteral(">\r\n                            <input autofocus");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"cancel\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n                        </form>\r\n                    </div>\r\n\r\n             " +
"   </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <script>\r\n            $(document).ready(function () {\r\n                $(" +
"\'#loader-wrapper\').removeClass(\'hide-bg\');\r\n                setTimeout(function " +
"() { $(\"#loader-wrapper\").css(\'display\', \'none\'); }, 500);\r\n            });\r\n   " +
"         $(\'#main-form-submit\').click(function (e) {\r\n                e.preventD" +
"efault();\r\n\r\n                var bValid = true;\r\n                $(document).fin" +
"d(\'input.required:visible\').each(function () {\r\n                    var formgrou" +
"p = $(this).closest(\'.form-group\');\r\n                    if ($(this).val() === \'" +
"\') {\r\n                        formgroup.addClass(\'has-error\');\r\n                " +
"        var label = formgroup.find(\'label.control-label\').text();\r\n\r\n           " +
"             console.log(formgroup.find(\'div\').index(0));\r\n                     " +
"   if ($(this).closest(\'.col-md-9\').find(\'span.help-block\').length == 0)\r\n      " +
"                      $(this).closest(\'.col-md-9\').append(\'<span class=\"help-blo" +
"ck\">The \' + label + \' field is required.</span>\');\r\n\r\n                        bV" +
"alid = false;\r\n                    } else {\r\n                        formgroup.r" +
"emoveClass(\'has-error\');\r\n                        formgroup.find(\'span.help-bloc" +
"k\').remove();\r\n                    }\r\n                });\r\n\r\n                if " +
"(bValid) {\r\n                    setTimeout(function () { $(\"#loader-wrapper\").cs" +
"s(\'display\', \'flex\'); }, 500);\r\n                    $(\"#loader-wrapper\").addClas" +
"s(\'hide-bg\');\r\n\r\n                    $(window).scrollTop(0);\r\n                  " +
"  $(\'body\').css(\'overflow\', \'hidden\');\r\n\r\n                    $(\'#main-form\').su" +
"bmit.disabled = true;\r\n                    $(\'#main-form\').submit();\r\n          " +
"      }\r\n            });\r\n        </script>\r\n");

            
            #line 416 "..\..\Views\Actions\Action.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 420 "..\..\Views\Actions\Action.cshtml"
Write(Html.RenderDelayed());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
