#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    
    #line 8 "..\..\Views\Actions\Action.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Actions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Entities;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Interfaces;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Core.Web.Utilities;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Enquiries.Entities;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Actions\Action.cshtml"
    using Realtair.Framework.Enquiries.Interfaces;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Actions/Action.cshtml")]
    public partial class _Views_Actions_Action_cshtml : System.Web.Mvc.WebViewPage<Realtair.Framework.Core.Web.Controllers.ActionsController.ActionViewModel>
    {
        public _Views_Actions_Action_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Actions\Action.cshtml"
  
    var detailsTemplate = "-";
    var cancelActionUrl = "";

    if (Request.QueryString["ReturnUrl"] != null)
    {
        cancelActionUrl = Request.QueryString["ReturnUrl"].ToString();
    }

    if (Model.Action.This != null)
    {
        detailsTemplate = $"{Model.Action.This.ActualType().Name}/{Model.Action.GetType().Name}";
    }

    if (Html.ViewExists(detailsTemplate))
    {
        Layout = null;
        Html.RenderPartial(detailsTemplate, Model.Action);
    }
    else
    {
        IEnumerable<Field> shown;
        IEnumerable<Field> shownWithFieldSets;
        IEnumerable<Field> hidden;

        TempData["ShowSubmit"] = true;

        if (Model.IsMultiPage)
        {
            shown = Model.FieldsForPage;
            shownWithFieldSets = Model.FieldsForPage.Where(f => f.FieldSetAttribute != null).ToList();
            hidden = Model.HiddenFieldsForPage;
        }
        else
        {
            shown = Model.Fields;
            shownWithFieldSets = Model.Fields.Where(f => f.FieldSetAttribute != null).ToList();
            hidden = null;
        }


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"content bg-grey-lt\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 51 "..\..\Views\Actions\Action.cshtml"
       Write(Html.Partial("FlowerHorn/MobileNavigation"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" id=\"page-wrapper\"");

WriteLiteral(" class=\"padding-sides-sm pad-form-mob\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-sm-10 col-sm-offset-1\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n                        <h2>\r\n");

            
            #line 57 "..\..\Views\Actions\Action.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Actions\Action.cshtml"
                             if (Model.IsMultiPage)
                            {
                                
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Actions\Action.cshtml"
                           Write(Model.Page.Name.ToUpper());

            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Actions\Action.cshtml"
                                                          
                            }
                            else
                            {
                                
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Actions\Action.cshtml"
                           Write(Model.Action.Description(Html.LoggedInUser()).ToUpper());

            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Actions\Action.cshtml"
                                                                                        
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </h2>\r\n\r\n");

            
            #line 67 "..\..\Views\Actions\Action.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Actions\Action.cshtml"
                         if(Model.Action.This is IHasParentEnquiry) 
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <h3");

WriteLiteral(" class=\"no-margin-tb\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-home\"");

WriteLiteral("></i> ");

            
            #line 70 "..\..\Views\Actions\Action.cshtml"
                                                       Write((Model.Action.This as IHasParentEnquiry)?.ParentEnquiry.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </h3>\r\n");

WriteLiteral("                            <br />\r\n");

            
            #line 73 "..\..\Views\Actions\Action.cshtml"
                        }

                        
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Actions\Action.cshtml"
                                               

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 76 "..\..\Views\Actions\Action.cshtml"
                         if (Model.Action.HasValidated && !Model.Action.IsValid)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" style=\"padding: 0;\"");

WriteLiteral(">\r\n");

            
            #line 79 "..\..\Views\Actions\Action.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Actions\Action.cshtml"
                                 foreach (var error in Model.Action.Errors.Where(e => e.MemberNames.Count() == 0))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">");

            
            #line 81 "..\..\Views\Actions\Action.cshtml"
                                                               Write(error.ErrorMessage);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 82 "..\..\Views\Actions\Action.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n");

            
            #line 84 "..\..\Views\Actions\Action.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <form");

WriteLiteral(" class=\"form-horizontal panel panel-body\"");

WriteLiteral(" id=\"main-form\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

            
            #line 124 "..\..\Views\Actions\Action.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\Actions\Action.cshtml"
                                     foreach (var field in shown)
                                    {
                                        if (field.FieldSetAttribute != null)
                                        {
                                            var fieldSetItems = shownWithFieldSets.Where(s => s.FieldSetAttribute.Legend == field.FieldSetAttribute.Legend).ToList();
                                            if (fieldSetItems.Any())
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <fieldset");

WriteLiteral(" style=\"padding: 1px;\"");

WriteLiteral(">\r\n                                                    <legend>");

            
            #line 132 "..\..\Views\Actions\Action.cshtml"
                                                       Write(field.FieldSetAttribute.Legend);

            
            #line default
            #line hidden
WriteLiteral("</legend>\r\n                                                    <div");

WriteLiteral(" class=\"p-l-30\"");

WriteLiteral(">\r\n");

            
            #line 134 "..\..\Views\Actions\Action.cshtml"
                                                        
            
            #line default
            #line hidden
            
            #line 134 "..\..\Views\Actions\Action.cshtml"
                                                         foreach (var item in fieldSetItems)
                                                        {
                                                            var fieldWithReturnType = $"Fields/_{item.PropertyType.Name}_{item.FieldAttribute.GetType().Name.Substring(0, item.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                                            var fieldWithoutReturnType = $"Fields/_{item.FieldAttribute.GetType().Name.Substring(0, item.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                                            var fieldThatWorksForBoth = $"Fields/_{item.PropertyType.Name}_Field";

                                                            if (Html.ViewExists(fieldWithReturnType))
                                                            {
                                                                Html.RenderPartial(fieldWithReturnType, item);
                                                            }
                                                            else if (Html.ViewExists(fieldWithoutReturnType))
                                                            {
                                                                Html.RenderPartial(fieldWithoutReturnType, item);
                                                            }
                                                            else if (Html.ViewExists(fieldThatWorksForBoth))
                                                            {
                                                                Html.RenderPartial(fieldThatWorksForBoth, item);
                                                            }
                                                            else
                                                            {


            
            #line default
            #line hidden
WriteLiteral("                                                                <p> Cannot render" +
" field view, looked for both ");

            
            #line 155 "..\..\Views\Actions\Action.cshtml"
                                                                                                         Write(fieldWithReturnType);

            
            #line default
            #line hidden
WriteLiteral(" and ");

            
            #line 155 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                  Write(fieldWithoutReturnType);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n");

            
            #line 156 "..\..\Views\Actions\Action.cshtml"

                                                            }
                                                        }

            
            #line default
            #line hidden
WriteLiteral("                                                    </div>\r\n                     " +
"                           </fieldset>");

            
            #line 160 "..\..\Views\Actions\Action.cshtml"
                                                           shownWithFieldSets = shownWithFieldSets.Except(fieldSetItems).ToList();
                                            }
                                        }
                                        else
                                        {
                                            var fieldWithReturnType = $"Fields/_{field.PropertyType.Name}_{field.FieldAttribute.GetType().Name.Substring(0, field.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                            var fieldWithoutReturnType = $"Fields/_{field.FieldAttribute.GetType().Name.Substring(0, field.FieldAttribute.GetType().Name.Length - "Attribute".Length)}";
                                            var fieldThatWorksForBoth = $"Fields/_{field.PropertyType.Name}_Field";

                                            if (Html.ViewExists(fieldWithReturnType))
                                            {
                                                Html.RenderPartial(fieldWithReturnType, field);
                                            }
                                            else if (Html.ViewExists(fieldWithoutReturnType))
                                            {
                                                Html.RenderPartial(fieldWithoutReturnType, field);
                                            }
                                            else if (Html.ViewExists(fieldThatWorksForBoth))
                                            {
                                                Html.RenderPartial(fieldThatWorksForBoth, field);
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <p>Cannot render field view, look" +
"ed for both ");

            
            #line 183 "..\..\Views\Actions\Action.cshtml"
                                                                                        Write(fieldWithReturnType);

            
            #line default
            #line hidden
WriteLiteral(" and ");

            
            #line 183 "..\..\Views\Actions\Action.cshtml"
                                                                                                                 Write(fieldWithoutReturnType);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 184 "..\..\Views\Actions\Action.cshtml"
                                            }
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 188 "..\..\Views\Actions\Action.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 188 "..\..\Views\Actions\Action.cshtml"
                                     if (hidden != null)
                                    {
                                        foreach (var field in hidden)
                                        {
                                            if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.BulkFileUploadFieldAttribute && field.Value is IEnumerable<Attachment>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 11543), Tuple.Create("\"", 11567)
            
            #line 194 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 11550), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 11550), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 11568), Tuple.Create("\"", 11654)
, Tuple.Create(Tuple.Create("", 11576), Tuple.Create("[", 11576), true)
, Tuple.Create(Tuple.Create("", 11577), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 194 "..\..\Views\Actions\Action.cshtml"
                                                                                                       foreach (var a in field.Value as IEnumerable<Attachment>) { 
            
            #line default
            #line hidden
            
            #line 194 "..\..\Views\Actions\Action.cshtml"
                                                                                                                             WriteTo(__razor_attribute_value_writer, a.Id + ",");

            
            #line default
            #line hidden
            
            #line 194 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                 }
            
            #line default
            #line hidden
}), 11577), false)
, Tuple.Create(Tuple.Create("", 11653), Tuple.Create("]", 11653), true)
);

WriteLiteral(" />\r\n");

            
            #line 195 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IList<Attachment>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 11910), Tuple.Create("\"", 11934)
            
            #line 198 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 11917), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 11917), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 11935), Tuple.Create("\"", 12026)
, Tuple.Create(Tuple.Create("", 11943), Tuple.Create("[", 11943), true)
            
            #line 198 "..\..\Views\Actions\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 11944), Tuple.Create<System.Object, System.Int32>(string.Join(",",((IList<Attachment>)field.Value).Select(f => f.Id.ToString()))
            
            #line default
            #line hidden
, 11944), false)
, Tuple.Create(Tuple.Create("", 12025), Tuple.Create("]", 12025), true)
);

WriteLiteral(" />\r\n");

            
            #line 199 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is ICustomViewModel)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 12281), Tuple.Create("\"", 12305)
            
            #line 202 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 12288), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 12288), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 12306), Tuple.Create("\"", 12362)
            
            #line 202 "..\..\Views\Actions\Action.cshtml"
                     , Tuple.Create(Tuple.Create("", 12314), Tuple.Create<System.Object, System.Int32>((field.Value as ICustomViewModel).Serialize()
            
            #line default
            #line hidden
, 12314), false)
);

WriteLiteral(" />\r\n");

            
            #line 203 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<ICustomViewModel>)
                                            {
                                                if ((field.Value as IEnumerable<ICustomViewModel>).Count() > 0)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 12798), Tuple.Create("\"", 12822)
            
            #line 208 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 12805), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 12805), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 12823), Tuple.Create("\"", 12927)
, Tuple.Create(Tuple.Create("", 12831), Tuple.Create("[", 12831), true)
            
            #line 208 "..\..\Views\Actions\Action.cshtml"
                          , Tuple.Create(Tuple.Create("", 12832), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<ICustomViewModel>).Select(s => s.Serialize()))
            
            #line default
            #line hidden
, 12832), false)
, Tuple.Create(Tuple.Create("", 12926), Tuple.Create("]", 12926), true)
);

WriteLiteral(" />\r\n");

            
            #line 209 "..\..\Views\Actions\Action.cshtml"
                                                }
                                            }
                                            else if (field.Value is IEnumerable<Entity>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 13236), Tuple.Create("\"", 13260)
            
            #line 213 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 13243), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 13243), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 13261), Tuple.Create("\"", 13357)
, Tuple.Create(Tuple.Create("", 13269), Tuple.Create("[", 13269), true)
            
            #line 213 "..\..\Views\Actions\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 13270), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<Entity>).Select(e => e.Id.ToString()))
            
            #line default
            #line hidden
, 13270), false)
, Tuple.Create(Tuple.Create("", 13356), Tuple.Create("]", 13356), true)
);

WriteLiteral(" />\r\n");

            
            #line 214 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is Entity)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 13602), Tuple.Create("\"", 13626)
            
            #line 217 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 13609), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 13609), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 13627), Tuple.Create("\"", 13664)
            
            #line 217 "..\..\Views\Actions\Action.cshtml"
                     , Tuple.Create(Tuple.Create("", 13635), Tuple.Create<System.Object, System.Int32>((field.Value as Entity).Id
            
            #line default
            #line hidden
, 13635), false)
);

WriteLiteral(" />\r\n");

            
            #line 218 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.WidgetFieldAttribute)
                                            {

                                            }
                                            else if (field.Value is bool?[])
                                            {
                                                var values = "";
                                                foreach (var v in (field.Value as IEnumerable<bool?>).ToList())
                                                {
                                                    if (v != null) { values += v + ","; }
                                                    else { values += "null,"; }

                                                }

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 14609), Tuple.Create("\"", 14633)
            
            #line 232 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 14616), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 14616), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 14634), Tuple.Create("\"", 14695)
, Tuple.Create(Tuple.Create("", 14642), Tuple.Create("[", 14642), true)
            
            #line 232 "..\..\Views\Actions\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 14643), Tuple.Create<System.Object, System.Int32>(values.Substring(0, values.Length - 1).ToLower()
            
            #line default
            #line hidden
, 14643), false)
, Tuple.Create(Tuple.Create("", 14694), Tuple.Create("]", 14694), true)
);

WriteLiteral(" />\r\n");

            
            #line 233 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is DateTime)
                                            {
                                                var date = (DateTime)field.Value;

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 15025), Tuple.Create("\"", 15049)
            
            #line 237 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 15032), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 15032), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 15050), Tuple.Create("\"", 15120)
, Tuple.Create(Tuple.Create("", 15058), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 237 "..\..\Views\Actions\Action.cshtml"
                                                                                                      if(date > DateTime.MinValue) { 
            
            #line default
            #line hidden
            
            #line 237 "..\..\Views\Actions\Action.cshtml"
                                                                                              WriteTo(__razor_attribute_value_writer, date.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
            
            #line 237 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                  }
            
            #line default
            #line hidden
}), 15058), false)
);

WriteLiteral(" />\r\n");

            
            #line 238 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is bool)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 15363), Tuple.Create("\"", 15387)
            
            #line 241 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 15370), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 15370), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 15388), Tuple.Create("\"", 15419)
            
            #line 241 "..\..\Views\Actions\Action.cshtml"
                    , Tuple.Create(Tuple.Create("", 15396), Tuple.Create<System.Object, System.Int32>(field.Value.ToString()
            
            #line default
            #line hidden
, 15396), false)
);

WriteLiteral(" />\r\n");

            
            #line 242 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 15637), Tuple.Create("\"", 15661)
            
            #line 245 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 15644), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 15644), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 15662), Tuple.Create("\"", 15682)
            
            #line 245 "..\..\Views\Actions\Action.cshtml"
                    , Tuple.Create(Tuple.Create("", 15670), Tuple.Create<System.Object, System.Int32>(field.Value
            
            #line default
            #line hidden
, 15670), false)
);

WriteLiteral(" />\r\n");

            
            #line 246 "..\..\Views\Actions\Action.cshtml"
                                            }
                                        }


            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"submittedpagenames\"");

WriteAttribute("value", Tuple.Create(" value=\"", 15866), Tuple.Create("\"", 15943)
            
            #line 249 "..\..\Views\Actions\Action.cshtml"
             , Tuple.Create(Tuple.Create("", 15874), Tuple.Create<System.Object, System.Int32>(string.Join(",", Model.SubmittedPages.Select(p => p.GetType().Name))
            
            #line default
            #line hidden
, 15874), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"page\"");

WriteAttribute("value", Tuple.Create(" value=\"", 16021), Tuple.Create("\"", 16055)
            
            #line 250 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 16029), Tuple.Create<System.Object, System.Int32>(Model.Page.GetType().Name
            
            #line default
            #line hidden
, 16029), false)
);

WriteLiteral(" />\r\n");

            
            #line 251 "..\..\Views\Actions\Action.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" style=\"position: absolute; left: -9999px; width: 1px; height: 1px;\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" />\r\n                                </form>\r\n\r\n");

            
            #line 256 "..\..\Views\Actions\Action.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 256 "..\..\Views\Actions\Action.cshtml"
                                 if ((bool)TempData["ShowSubmit"] || Model.SubmittedPages.Count != 0)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <div");

WriteLiteral(" class=\"form-group margin-tb-md\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                            <ul");

WriteLiteral(" class=\"pull-right list-inline\"");

WriteLiteral(">\r\n");

            
            #line 261 "..\..\Views\Actions\Action.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 261 "..\..\Views\Actions\Action.cshtml"
                                                 if ((bool)TempData["ShowSubmit"])
                                                {
                                                    if (!Model.IsMultiPage)
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-green uppercase\"");

WriteLiteral(" onclick=\'$(\"#main-form\").submit();\'");

WriteLiteral(">");

            
            #line 265 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                 Write(Model.Action.SubmitValue);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 266 "..\..\Views\Actions\Action.cshtml"
                                                    }
                                                    else
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-grey uppercase\"");

WriteLiteral(" onclick=\'$(\"#main-form\").submit();\'");

WriteLiteral(">");

            
            #line 269 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                Write(Model.Action.SubmitValue);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 270 "..\..\Views\Actions\Action.cshtml"
                                                    }
                                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 273 "..\..\Views\Actions\Action.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 273 "..\..\Views\Actions\Action.cshtml"
                                                 if (Model.SubmittedPages.Count != 0)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-grey uppercase\"");

WriteLiteral(" onclick=\'$(\"#back-form\").submit();\'");

WriteLiteral(">BACK</a></li>\r\n");

            
            #line 276 "..\..\Views\Actions\Action.cshtml"
                                                }
                                                else
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"btn btn-task btn-form btn-trans-red uppercase\"");

WriteLiteral(" onclick=\'$(\"#cancel-form\").submit();\'");

WriteLiteral(">CANCEL</a></li>\r\n");

            
            #line 280 "..\..\Views\Actions\Action.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </ul>\r\n                              " +
"          </div>\r\n                                    </div>\r\n");

            
            #line 284 "..\..\Views\Actions\Action.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\r\n                        </div>\r\n\r\n");

            
            #line 288 "..\..\Views\Actions\Action.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 288 "..\..\Views\Actions\Action.cshtml"
                         if (Model.IsMultiPage)
                        {
                            if (Model.SubmittedPages.Count != 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" id=\"back-form\"");

WriteLiteral(">\r\n");

            
            #line 293 "..\..\Views\Actions\Action.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 293 "..\..\Views\Actions\Action.cshtml"
                                     if (hidden != null)
                                    {
                                        foreach (var field in hidden)
                                        {
                                            if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.BulkFileUploadFieldAttribute && field.Value is IEnumerable<Attachment>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 19366), Tuple.Create("\"", 19390)
            
            #line 299 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 19373), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 19373), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 19391), Tuple.Create("\"", 19477)
, Tuple.Create(Tuple.Create("", 19399), Tuple.Create("[", 19399), true)
, Tuple.Create(Tuple.Create("", 19400), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 299 "..\..\Views\Actions\Action.cshtml"
                                                                                                       foreach (var a in field.Value as IEnumerable<Attachment>) { 
            
            #line default
            #line hidden
            
            #line 299 "..\..\Views\Actions\Action.cshtml"
                                                                                                                             WriteTo(__razor_attribute_value_writer, a.Id + ",");

            
            #line default
            #line hidden
            
            #line 299 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                 }
            
            #line default
            #line hidden
}), 19400), false)
, Tuple.Create(Tuple.Create("", 19476), Tuple.Create("]", 19476), true)
);

WriteLiteral(" />\r\n");

            
            #line 300 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<Attachment>)
                                            {
                                                foreach (var file in (IEnumerable<Attachment>)field.Value)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 19902), Tuple.Create("\"", 19926)
            
            #line 305 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 19909), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 19909), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 19927), Tuple.Create("\"", 19945)
            
            #line 305 "..\..\Views\Actions\Action.cshtml"
                         , Tuple.Create(Tuple.Create("", 19935), Tuple.Create<System.Object, System.Int32>(file.Id
            
            #line default
            #line hidden
, 19935), false)
);

WriteLiteral(" />");

            
            #line 305 "..\..\Views\Actions\Action.cshtml"
                                                                                                                       }
                                            }
                                            else if (field.Value is ICustomViewModel)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 20201), Tuple.Create("\"", 20225)
            
            #line 309 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 20208), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 20208), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 20226), Tuple.Create("\"", 20282)
            
            #line 309 "..\..\Views\Actions\Action.cshtml"
                     , Tuple.Create(Tuple.Create("", 20234), Tuple.Create<System.Object, System.Int32>((field.Value as ICustomViewModel).Serialize()
            
            #line default
            #line hidden
, 20234), false)
);

WriteLiteral(" />\r\n");

            
            #line 310 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<ICustomViewModel>)
                                            {
                                                if ((field.Value as IEnumerable<ICustomViewModel>).Count() > 0)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 20718), Tuple.Create("\"", 20742)
            
            #line 315 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 20725), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 20725), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 20743), Tuple.Create("\"", 20847)
, Tuple.Create(Tuple.Create("", 20751), Tuple.Create("[", 20751), true)
            
            #line 315 "..\..\Views\Actions\Action.cshtml"
                          , Tuple.Create(Tuple.Create("", 20752), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<ICustomViewModel>).Select(s => s.Serialize()))
            
            #line default
            #line hidden
, 20752), false)
, Tuple.Create(Tuple.Create("", 20846), Tuple.Create("]", 20846), true)
);

WriteLiteral(" />");

            
            #line 315 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                                                             }
                                            }
                                            else if (field.Value is Entity)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 21093), Tuple.Create("\"", 21117)
            
            #line 319 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 21100), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 21100), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 21118), Tuple.Create("\"", 21155)
            
            #line 319 "..\..\Views\Actions\Action.cshtml"
                     , Tuple.Create(Tuple.Create("", 21126), Tuple.Create<System.Object, System.Int32>((field.Value as Entity).Id
            
            #line default
            #line hidden
, 21126), false)
);

WriteLiteral(" />\r\n");

            
            #line 320 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is IEnumerable<Entity>)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 21413), Tuple.Create("\"", 21437)
            
            #line 323 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 21420), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 21420), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 21438), Tuple.Create("\"", 21534)
, Tuple.Create(Tuple.Create("", 21446), Tuple.Create("[", 21446), true)
            
            #line 323 "..\..\Views\Actions\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 21447), Tuple.Create<System.Object, System.Int32>(string.Join(",", (field.Value as IEnumerable<Entity>).Select(e => e.Id.ToString()))
            
            #line default
            #line hidden
, 21447), false)
, Tuple.Create(Tuple.Create("", 21533), Tuple.Create("]", 21533), true)
);

WriteLiteral(" />\r\n");

            
            #line 324 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.FieldAttribute is Realtair.Framework.Core.Actions.FieldAttributes.WidgetFieldAttribute)
                                            {

                                            }
                                            else if (field.Value is bool?[])
                                            {
                                                var values = "";
                                                foreach (var v in (field.Value as IEnumerable<bool?>).ToList())
                                                {
                                                    if (v != null) { values += v + ","; }
                                                    else { values += "null,"; }

                                                }

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 22479), Tuple.Create("\"", 22503)
            
            #line 338 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 22486), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 22486), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 22504), Tuple.Create("\"", 22565)
, Tuple.Create(Tuple.Create("", 22512), Tuple.Create("[", 22512), true)
            
            #line 338 "..\..\Views\Actions\Action.cshtml"
                      , Tuple.Create(Tuple.Create("", 22513), Tuple.Create<System.Object, System.Int32>(values.Substring(0, values.Length - 1).ToLower()
            
            #line default
            #line hidden
, 22513), false)
, Tuple.Create(Tuple.Create("", 22564), Tuple.Create("]", 22564), true)
);

WriteLiteral(" />\r\n");

            
            #line 339 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is DateTime)
                                            {
                                                var date = (DateTime)field.Value;

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 22895), Tuple.Create("\"", 22919)
            
            #line 343 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 22902), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 22902), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 22920), Tuple.Create("\"", 22990)
, Tuple.Create(Tuple.Create("", 22928), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 343 "..\..\Views\Actions\Action.cshtml"
                                                                                                      if(date > DateTime.MinValue) { 
            
            #line default
            #line hidden
            
            #line 343 "..\..\Views\Actions\Action.cshtml"
                                                                                              WriteTo(__razor_attribute_value_writer, date.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
            
            #line 343 "..\..\Views\Actions\Action.cshtml"
                                                                                                                                                                  }
            
            #line default
            #line hidden
}), 22928), false)
);

WriteLiteral(" />\r\n");

            
            #line 344 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else if (field.Value is bool)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 23233), Tuple.Create("\"", 23257)
            
            #line 347 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 23240), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 23240), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 23258), Tuple.Create("\"", 23289)
            
            #line 347 "..\..\Views\Actions\Action.cshtml"
                    , Tuple.Create(Tuple.Create("", 23266), Tuple.Create<System.Object, System.Int32>(field.Value.ToString()
            
            #line default
            #line hidden
, 23266), false)
);

WriteLiteral(" />\r\n");

            
            #line 348 "..\..\Views\Actions\Action.cshtml"
                                            }
                                            else
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 23507), Tuple.Create("\"", 23531)
            
            #line 351 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 23514), Tuple.Create<System.Object, System.Int32>(field.UniqueName
            
            #line default
            #line hidden
, 23514), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 23532), Tuple.Create("\"", 23552)
            
            #line 351 "..\..\Views\Actions\Action.cshtml"
                    , Tuple.Create(Tuple.Create("", 23540), Tuple.Create<System.Object, System.Int32>(field.Value
            
            #line default
            #line hidden
, 23540), false)
);

WriteLiteral(" />\r\n");

            
            #line 352 "..\..\Views\Actions\Action.cshtml"
                                            }
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"submittedpagenames\"");

WriteAttribute("value", Tuple.Create(" value=\"", 23734), Tuple.Create("\"", 23811)
            
            #line 354 "..\..\Views\Actions\Action.cshtml"
             , Tuple.Create(Tuple.Create("", 23742), Tuple.Create<System.Object, System.Int32>(string.Join(",", Model.SubmittedPages.Select(p => p.GetType().Name))
            
            #line default
            #line hidden
, 23742), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"page\"");

WriteAttribute("value", Tuple.Create(" value=\"", 23889), Tuple.Create("\"", 23923)
            
            #line 355 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 23897), Tuple.Create<System.Object, System.Int32>(Model.Page.GetType().Name
            
            #line default
            #line hidden
, 23897), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"back\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n");

            
            #line 357 "..\..\Views\Actions\Action.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </form>\r\n");

            
            #line 359 "..\..\Views\Actions\Action.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <form");

WriteLiteral(" method=\"post\"");

WriteLiteral(" id=\"cancel-form\"");

WriteAttribute("action", Tuple.Create(" action=\"", 24217), Tuple.Create("\"", 24244)
            
            #line 361 "..\..\Views\Actions\Action.cshtml"
, Tuple.Create(Tuple.Create("", 24226), Tuple.Create<System.Object, System.Int32>(cancelActionUrl
            
            #line default
            #line hidden
, 24226), false)
);

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"cancel\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n                        </form>\r\n                    </div>\r\n\r\n             " +
"   </div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral(@"        <script>
            $('#main-form-submit').click(function (e) {
				e.preventDefault()
				var bValid = true;
				$(document).find('input.required:visible').each(function () {
					var formgroup = $(this).closest('.form-group');
					if ($(this).val() === '') {
						formgroup.addClass('has-error');
						var label = formgroup.find('label.control-label').text();

						console.log(formgroup.find('div').index(0));
						if ($(this).closest('.col-md-9').find('span.help-block').length == 0)
							$(this).closest('.col-md-9').append('<span class=""help-block"">The ' + label + ' field is required.</span>');

						bValid = false;
					} else {
						formgroup.removeClass('has-error');
						formgroup.find('span.help-block').remove();
					}
				});

				if (bValid) {
					$('.preloader').css('display', 'block');
					$('#main-form').submit.disabled = true;
					$('#main-form').submit();
				}
			});
        </script>
");

            
            #line 397 "..\..\Views\Actions\Action.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 401 "..\..\Views\Actions\Action.cshtml"
Write(Html.RenderDelayed());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
