#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Actions/EmptyAction.cshtml")]
    public partial class _Views_Actions_EmptyAction_cshtml : System.Web.Mvc.WebViewPage<Realtair.Framework.Core.Web.Controllers.ActionsController.ActionViewModel>
    {
        public _Views_Actions_EmptyAction_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"<body id=""page-confirmation"" class=""animate-in"">
    <div class=""loading"" style=""display: none;""><span class=""message"">Loading...</span></div>
    <div class=""container text-center"">
        <div class=""content-table"">
            <div class=""content-vertical middle"">
                <div class=""row"">
                    <div class=""col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-lg-3 col-lg-offset-4"">
                        <h1>");


            
            #line 9 "..\..\Views\Actions\EmptyAction.cshtml"
                       Write(Model.Action.Description(Html.LoggedInUser()));

            
            #line default
            #line hidden
WriteLiteral(@"</h1>
                        <div class=""pull-middle"">
                            <a onclick=""$('#main-form').submit()"" class=""btn-primary btn-lg btn"">Confirm</a>
                            <a class=""btn-warning btn-lg btn"" href=""/"">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form style=""display: none;"" id=""main-form"" method=""POST""></form>
</body>");


        }
    }
}
#pragma warning restore 1591
