#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Realtair.Framework.Core.Actions;
    using Realtair.Framework.Core.Entities;
    using Realtair.Framework.Core.Interfaces;
    using Realtair.Framework.Core.Web.Utilities;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Fields/_ColourPickerField.cshtml")]
    public partial class _Views_Shared_Fields__ColourPickerField_cshtml : System.Web.Mvc.WebViewPage<Realtair.Framework.Core.Actions.Field>
    {
        public _Views_Shared_Fields__ColourPickerField_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-2 col-sm-2\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 5 "..\..\Views\Shared\Fields\_ColourPickerField.cshtml"
                                Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"col-md-10 col-sm-10\"");

WriteLiteral(">\r\n        <input");

WriteAttribute("id", Tuple.Create(" id=\"", 237), Tuple.Create("\"", 259)
            
            #line 9 "..\..\Views\Shared\Fields\_ColourPickerField.cshtml"
, Tuple.Create(Tuple.Create("", 242), Tuple.Create<System.Object, System.Int32>(Model.UniqueName
            
            #line default
            #line hidden
, 242), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 260), Tuple.Create("\"", 284)
            
            #line 9 "..\..\Views\Shared\Fields\_ColourPickerField.cshtml"
, Tuple.Create(Tuple.Create("", 267), Tuple.Create<System.Object, System.Int32>(Model.UniqueName
            
            #line default
            #line hidden
, 267), false)
);

WriteLiteral(" type=\"text\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 297), Tuple.Create("\"", 337)
            
            #line 9 "..\..\Views\Shared\Fields\_ColourPickerField.cshtml"
         , Tuple.Create(Tuple.Create("", 311), Tuple.Create<System.Object, System.Int32>(Model.FieldAttribute.Hint
            
            #line default
            #line hidden
, 311), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 338), Tuple.Create("\"", 358)
            
            #line 9 "..\..\Views\Shared\Fields\_ColourPickerField.cshtml"
                                            , Tuple.Create(Tuple.Create("", 346), Tuple.Create<System.Object, System.Int32>(Model.Value
            
            #line default
            #line hidden
, 346), false)
);

WriteLiteral(" class=\"jscolor form-control\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" src=\"https://static.realtair.com/js/jscolor.min.js\"");

WriteLiteral("></script>\r\n<script>\r\n    $(function () {\r\n        $(\'#");

            
            #line 16 "..\..\Views\Shared\Fields\_ColourPickerField.cshtml"
       Write(Model.UniqueName);

            
            #line default
            #line hidden
WriteLiteral("\').css(\'background-color\', \'#");

            
            #line 16 "..\..\Views\Shared\Fields\_ColourPickerField.cshtml"
                                                     Write(Model.Value);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
