#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Realtair.Framework.Core.Actions;
    using Realtair.Framework.Core.Entities;
    using Realtair.Framework.Core.Interfaces;
    using Realtair.Framework.Core.Web.Utilities;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Fields/_DateTime_Field.cshtml")]
    public partial class _Views_Shared_Fields__DateTime_Field_cshtml : System.Web.Mvc.WebViewPage<Realtair.Framework.Core.Actions.Field>
    {
        public _Views_Shared_Fields__DateTime_Field_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
  
    var attribute = Model.FieldAttribute as Realtair.Framework.Core.Actions.FieldAttributes.DateTimeFieldAttribute;
    var Date = Convert.ToDateTime(Model.Value);
    var dateFormat = "yyyy-MM-dd";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-3 col-sm-4\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 11 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
                                Write(Model.Label);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"col-md-9 col-sm-8\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n            <input");

WriteAttribute("name", Tuple.Create(" \r\n                   name=\"", 485), Tuple.Create("\"", 530)
            
            #line 17 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
, Tuple.Create(Tuple.Create("", 513), Tuple.Create<System.Object, System.Int32>(Model.UniqueName
            
            #line default
            #line hidden
, 513), false)
);

WriteLiteral(" \r\n                   type=\"text\"");

WriteLiteral("\r\n                   class=\"form-control mydatepicker input-small\"");

WriteAttribute("value", Tuple.Create("\r\n                   value=\"", 630), Tuple.Create("\"", 719)
, Tuple.Create(Tuple.Create("", 658), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 20 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
                           if (Date > DateTime.MinValue) { 
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
                    WriteTo(__razor_attribute_value_writer, Date.ToString(dateFormat));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
                                                                                      }
            
            #line default
            #line hidden
}), 658), false)
);

WriteAttribute("placeholder", Tuple.Create("\r\n                   placeholder=\"", 720), Tuple.Create("\"", 765)
            
            #line 21 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
, Tuple.Create(Tuple.Create("", 754), Tuple.Create<System.Object, System.Int32>(dateFormat
            
            #line default
            #line hidden
, 754), false)
);

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"mdi mdi-calendar-blank\"");

WriteLiteral("></i>\r\n            </span>\r\n");

            
            #line 25 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
            
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
             if (Model.HasError)
            {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"help-block\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
                                    Write(Model.ErrorMessage);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 28 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n\r\n");

            
            #line 33 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
 using (Html.Delayed(null, "date-time-field"))
{

            
            #line default
            #line hidden
WriteLiteral("    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"https://static.realtair.com/plugins/bower_components/bootstrap-datepicker/" +
"bootstrap-datepicker.min.css\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n");

WriteLiteral("    <script");

WriteLiteral(" src=\"https://static.realtair.com/plugins/bower_components/bootstrap-datepicker/b" +
"ootstrap-datepicker.min.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    <script>\r\n        $(function () {\r\n            $(\'.mydatepicker\').datepicker(" +
"{\r\n                format: \'");

            
            #line 40 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
                    Write(dateFormat);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n");

WriteLiteral("                ");

            
            #line 41 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
           Write(Html.Raw(attribute != null && !attribute.AllowPastDates ? "startDate: '+0d'," : ""));

            
            #line default
            #line hidden
WriteLiteral("\r\n                autoclose: true\r\n            })\r\n        })\r\n    </script>\r\n");

            
            #line 46 "..\..\Views\Shared\Fields\_DateTime_Field.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
